### PR TITLE
feat(): Introduced new @kestra/ui library

### LINKED ISSUE #1670: ⭐ Topology Design Revamp
### Feature description

Epic Issue:

- #774 
- #1484 
- #241 
- #1758

### LINKED ISSUE #1721: Extract topologies on external package
We only want to be able to display topology right now in read only on the website.
So the first though is to : 
- extract the VueFlow part with all the box
- the drawser should not be included 
- we should not have dependencies on element-plus 
- the edit must work but only emit events

### PR DESCRIPTION
**Pull request by Skraye**
There is still open subflow link to do (and probably some fixes)

Reviews with : https://github.com/kestra-io/ui-libs

close #1721
close #1670

### CODE REVIEW

**Comment by Skraye** [comment]
image

Handle style only applies to the right, making the left one visible

**Comment by brian-mulier-p** [comment]
When creating a flow entering in editor - doc mode then switch directly to editor - topo or topo view, it doesn't recenter (add a switch view listener to recenter ?)
image

**Comment by brian-mulier-p** [comment]
full topo view misses style for the switch orientation button
image

**Comment by brian-mulier-p** [comment]
I think it lacks a hover effect on the + signs to show it's interactible

**Comment by brian-mulier-p** [comment]
Reloading page on editor - topo or topo only view doesn't show icon (you have to edit something before it shows or switch the view back and forth

**Comment by brian-mulier-p** [comment]
:warning: Adding task through low code seems not to work (it looks to do nothing, no error in console). It also doesn't do anything to source code
After investigation, it looks like it adds an error task instead of a standard task :thinking: 
image
```
id: hello-world2
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
  - id: dag
    type: io.kestra.core.tasks.flows.Dag
    tasks:
      - task:
          id: a
          type: io.kestra.core.tasks.log.Log
          message: e
        dependsOn:
          - b
      - task:
          id: b
          type: io.kestra.core.tasks.log.Log
          message: b
```
(tried to click on the '+' sign at the bottom of the flow graph)

**Comment by brian-mulier-p** [comment]
Information button on DAG task (but probably is the case for every flowable :thinking:) opens a "new task" form

**Comment by brian-mulier-p** [comment]
In the above example, deleting 'a' task from topo replaces 'a' task with 
```
- task: null
  dependsOn:
    - b
```
Still topo is not updated at all

deleting 'b' task from topo replaces 'b' task with 
```
- ? task
```
Same thing, topo is not updated at all

**Comment by brian-mulier-p** [comment]
Don't know if you have control over it but would be great to have a bigger offset to prevent '+' signs from being in-between cluster & non-cluster zone
image

**Comment by Skraye** [comment]
FYI @tchiotludo 
* No popper component yet
* Need to trick with translation (use of `t('')` in the package but use app translation)
* Icon information for task error > need to use another (more disturbing with the new visual)

**Pull request merged**
