### PR TITLE
fix(ui): UI adjustement on foreach progress

### PR DESCRIPTION
**Pull request by Skraye**

### CODE REVIEW

**Comment by Skraye** [comment]
close #2487

**Comment by Skraye** [comment]
close #2484

**Comment by brian-mulier-p** [comment]
image
Putting wrong "items" field (not a kestra URI but a list for eg.) won't show logs at all from Gantt view

**Comment by brian-mulier-p** [comment]
Don't know if it's related but going to Logs, even though it says it is expanded, is unexpanded and clicking to "unexpand" expands it instead
image

**Comment by Skraye** [comment]
> btw the logs is duplicated (but I think it's unrelated, might be worth an issue, should I create one or you're handling it here ?)
Not related to the UI, maybe worth waiting for Loic subflow refacto before opening an issue

**Pull request merged**
