### PR TITLE
feat(ui): add cURL command to execute window

### LINKED ISSUE #3585: Add a "Copy as cURL" button to the execute window
### Feature description

Executing a flow from the UI is easy, it include a form for the input and allow passing labels.

But doing the same from cURL is a bit tedious as inputs should be passed as form data and labels as query param.

Adding a button "Copy as cURL" or any other way to retrieve a cURL command to create an execution based on the parameters filled in the Execute window would be very convenient.

image

### PR DESCRIPTION
**Pull request by yuri1969**
### What changes are being made and why?

* Provided just the UNIX shell version - no support for Windows CMD/PowerShell.
* Displayed the cURL command preview as it IMHO improves the UX - the user actually sees what is copied. However, it can easily be transformed to just the _Copy as cURL_ button.
* The `FILE` input can't be really supported since browser doesn't have the full path.
* User credentials nor `SECRET` inputs should be presented.
* Componentized the copy-to-clipboard button.
* The French translation was done via Google Translate, sorry.

closes #3585

20240711-195924_snap

### CODE REVIEW

**Comment by loicmathieu** [comment]
Thanks a lot! This is very great!

Before one of our frontend experts reviews it, may I propose some enhancements?

- For SECRET input type, you can add them with `******` as the value.
- For FILE input type, they are the more complex as we use specific handling, so it would be great to show how to works by considering files are in the current working directory, so if a user have an input `myfile.txt` it generates a curl that will upload the `myfile.txt` from the current directory.
- With these changes the WARNING cloud be updated to something like 'Note that for SECRET and FILE input type, the command must be accommodate to match the real values'.
- Can you remove the Transfert-Encoding header, it is not mandatory

**Comment by yuri1969** [comment]
@loicmathieu Done

**Comment by loicmathieu** [comment]
Thanks @yuri1969 , I'll let Milos do a review

**Review by MilosPaunovic — APPROVED** [review]

**Comment by MilosPaunovic** [comment]
This has been done wonderfully, thanks a lot @yuri1969 and keep up the good work! 🚀

**Pull request merged**
