### PR TITLE
fix(ui): output download close #96

### LINKED ISSUE #96: File download from execution seems broken
You cannot download back a file input

"Download" button link is :
[https://.../5tp1dN4YDNDCoZY1DB3PWG/file?filePath=undefined&type=undefined](https://.../undefined/api/v1/executions/5tp1dN4YDNDCoZY1DB3PWG/file?filePath=undefined&type=undefined)

It doesn't download anything :man_shrugging: 
`filePath=undefined&type=undefined` looks wrong

### PR DESCRIPTION
**Pull request by eregnier**

### CODE REVIEW

**Comment by tchiotludo** [comment]
Glad to see your their 😅

I've just see this is security issue here.
You pass the full url to the controller.
It will me be more complicated to control that the download is from the current execution.
Why not pass the type `input` or `output` and the name of the input or the output. 
The controller will fetch the right url without passing it.
What do you think about that ?

**Comment by eregnier** [comment]
this was almost the previous behavior. but it was broken since the outlut value changef from dict to string uri, so this issue was created. I may indeed try to keep previous behavior if you prefer. 

let me know, i'll update this pr asap.

**Comment by eregnier** [comment]
It should be better now.

**Comment by tchiotludo** [comment]
Yes this is the right way, but it will break output download now no ?

**Comment by tchiotludo** [comment]
close in favor of 90c570c

**Pull request closed without merging**
