### PR TITLE
feat(core): add allowWarning property

### LINKED ISSUE #1926: Add `allowWarnings` boolean flag to the core task property allowing to mark a task run as Success despite warnings
Often some tasks emit warnings that are not important enough to prevent marking the task execution as Success. 

We should add a property `allowWarnings` (or if you prefer `ignoreWarnings`) = a boolean flag to allow a task run with warnings to be marked as Success:

```yaml
id: fail
namespace: company.team
tasks:
  - id: warn
    type: io.kestra.plugin.core.execution.Fail
    allowFailure: true
    allowWarnings: true
```

### PR DESCRIPTION
**Pull request by Skraye**
close #1926

### CODE REVIEW

**Comment by loicmathieu** [comment]
@Skraye did you check that we don't already have this property on some tasks (I'm thinking of the script tasks for ex)?

**Comment by loicmathieu** [comment]
I'm not fan of a task that FAILS that, if allowFailure and allowWarning will ends in SUCCESS, are you sure it's a good idea?

Most of the cases, warning comes from a log in warning, can you add a test for that?

**Comment by Skraye** [comment]
> @Skraye did you check that we don't already have this property on some tasks (I'm thinking of the script tasks for ex)?

AFAIK, we don't have this property on another plugin, even in the script one

**Comment by loicmathieu** [comment]
On script it's `warningOnStdErr` we may want to deprecate it to avoid too many properties doing almost the same thing.

**Comment by Skraye** [comment]
`warningOnStdErr` does a different thing, more related to logs
I agree they are pretty close, but they don't do the same thing

**Pull request merged**
