### PR TITLE
Removed the background behind the search input.

### LINKED ISSUE #6180: Plugins page: Remove the background behind the search input.
### Describe the issue

Remove the background behind the search input.

Capture d’écran 2024-11-28 à 16 52 58

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by JoeCelaster**
### What changes are being made and why?

- Here I replaced the background-color into Background into None
- Added a 1px solid border to .search.
- For html.dark (dark theme): Background: Changed to transparent
- Border Color: Set to a dark gray color (#404559)

### How the changes have been QAed?

 ```
.search {
        display: flex;
        width: 22rem;
        padding: 0.25rem 2rem;
        justify-content: center;
        align-items: center;
        gap: 0.25rem;
        background: none;
        border: 1px solid var(--bs-gray-300);
    }

    html.dark .search {
        background: transparent; 
        border-color: #404559; 
    }
```

Closes https://github.com/kestra-io/kestra/issues/6180.

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]
I've pushed a change that will amend the required issue, but you've guided me to the proper solution, so thanks for that @JoeCelaster! 🚀 

Will be merged soon, after we got our release up and running.

**Comment by MilosPaunovic** [comment]
Just a small note for the future, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).

**Comment by JoeCelaster** [comment]
> Just a small note for the future, if you could use **GitHub Keywords** when opening PRs to connect it to the proper issue (to automate the entire process a bit more), it would be super helpful to us. You can read a bit more about it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) (I've added closing keyword for this particular issue).
Firstly Thanks @MilosPaunovic for merging my pull request, and also thanks for the information i will follow this in future, Thank you !!.

**Comment by JoeCelaster** [comment]
Firstly Thanks @MilosPaunovic  for merging my pull request, and also thanks for the information i will follow this in future, Thank you !!.

**Pull request merged**
