### PR TITLE
Added multiselect filter for Namespace on Dashboard (#5156)

### PR DESCRIPTION
**Pull request by ssparser**
What changes are being made and why?
Added multiselect filter for Namespace on Dashboard 

How the changes have been QAed? 
manually checked the changes by running the application on localhost.

Screenshot 2024-10-12 at 1 16 47 AM
Screenshot 2024-10-12 at 1 17 08 AM

### CODE REVIEW

**Comment by ssparser** [comment]
hey @anna-geller, @MilosPaunovic  can you guys check the PR.

**Comment by MilosPaunovic** [comment]
This seems alright so far @ssparser, but it can't be merged until there are backend changes added, for everything to work properly. I'll ping @Skraye to check if the changes on the BE are significant, and should we put this on a temporary hold?

**Comment by Skraye** [comment]
Hello, this has been discussed on Slack, here is what the backend needs to have the feature fully work:

> * Repositories have to be modified to create a new method accepting multiples namespaces
>* Multiples controller have to be duplicated/modified to allows multiple namespace (but we may not want to break previous endpoint)
>* Those new endpoints/methods have to be tested

**Comment by MilosPaunovic** [comment]
Hi @ssparser,

Will have to close this PR as we've decided to handle issue https://github.com/kestra-io/kestra/issues/4664 now, and it will make multiple selection of namespace filters in this manner obsolete.

We really appreciate your efforts on this, and have to say you've done a great job on the UI part, exactly what we wanted at the time, so I'd like to encourage you to check out [this filtered list of good first issues](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and pick out something else you think you can solve.

Cheers! 🚀

**Pull request closed without merging**
