### PR TITLE
feat/specify-amount-of-rendering-in-raw-tag

### LINKED ISSUE #2740: Disable Pebble rendering on webhook trigger variables (keep rendering secrets/env vars on key, but don't parse the trigger body)
## Problem 

Take the following flow as example:

```yaml
id: github_to_notion
namespace: product

concurrency:
  behavior: QUEUE
  limit: 1

inputs:
  - name: github_url
    type: STRING
    defaults: https://github.com/kestra-io/docs/issues/678

variables:
  github_url: "{{ trigger.body.pull_request.html_url ?? trigger.body.issue.html_url ?? inputs.github_url }}"

tasks:
  - id: github_to_notion
    type: io.kestra.plugin.scripts.python.Commands
    warningOnStdErr: false
    env:
      GITHUB_TOKEN: "{{ secret('GITHUB_TOKEN') }}"
      NOTION_TOKEN: "{{ secret('NOTION_TOKEN') }}"
      DATABASE_ID: "81a8f4c0b1af4f3481da3b9bcab5537b"
    beforeCommands:
      - pip install requests markdown2 beautifulsoup4 --no-warn-script-location
    runner: PROCESS
    namespaceFiles:
      enabled: true
    commands:
      - python scripts/github_to_notion.py "{{ vars.github_url }}"

triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
    key: "mykey"
```

It takes a GitHub issue URL and loads it to Notion.  

The execution triggered by a webhook fails with error:

```
Missing variable: 'secrets' on 'Hi, I've set-up a github action as per readme.
...
Root attribute [secrets] does not exist or can not be accessed and strict variables is set to true.
```

## Suggested solution

Disable Pebble rendering on webhook trigger variables. 

image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
[Screencast from 27-12-2023 19:16:08.webm](https://github.com/kestra-io/kestra/assets/37618489/9d593c29-d783-4108-9fee-de21dcb11a0e)

closes #2740

### CODE REVIEW

**Comment by loicmathieu** [comment]
`raw` means not rendered, I don't feel comfortable hoisting a 'limiting rendering functionality' into it.

**Comment by Skraye** [comment]
Agree with @loicmathieu 
Seeing the example `Rendered twice: {% raw 2 %}{{ recursive_recursive_var }}{% endraw %};` It don't feel very clear what it does, I think we should have a `raw` AND a `maxRender`

**Comment by brian-mulier-p** [comment]
I did that to limit the amount of tags we introduce and how much specific loops there is in the rendering function but I can change the tag as u wish

**Comment by anna-geller** [comment]
thanks for adding this. Could you add a short explanation with some examples of what is meant by the amount of rendering?  is it the depth of JSON in the trigger payload? how we can make this more intuitive?

**Comment by brian-mulier-p** [comment]
Moved to draft as we won't tackle the recursive vs non-recursive approach for 0.14.0. Will be tackled for 0.15.0

**Comment by tchiotludo** [comment]
close in favor of https://github.com/kestra-io/kestra/pull/2834

**Pull request closed without merging**
