### PR TITLE
feat(editor): integrate tabbed and flow editing features into MonacoEditor

### LINKED ISSUE #5748: MonacoEditor should be a simple component
Now the [monaco editor](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/inputs/MonacoEditor.vue) is becoming crazy complex. 

We have too many logic inside that can break the principle of simple component for one use case. 
We should have IMO: 
- a `MonacoEditor` that have only 1 goal: configure an editor for our all the use case
- a `TabbedMonacoEditor` that will managed multiple tabs 
- and probably a `FlowMonacoEditor` that will contains all the logic for a flow 

Now all of theses is inside the same Files, making complex (if not impossible) to be sure that the simple use cases (yaml editor) works as expected.

### PR DESCRIPTION
**Pull request by Manpreets59**
- closes #5748

### What changes are being made and why?
This PR introduces enhancements to the MonacoEditor component by integrating tabbed editing functionality and flow content management. This addresses issue #5748, allowing users to seamlessly switch between multiple code files and edit flow-related content within a single editor instance. The changes improve the user experience by providing a more versatile and efficient editing environment.

### How the changes have been QAed?
The changes have been QAed by implementing the following example flow, which demonstrates the new tabbed and flow editing capabilities:
# Example flow code demonstrating the use of the new TabbedMonacoEditor and FlowMonacoEditor components

name: Example Flow with Monaco Editor
description: A flow that utilizes the enhanced MonacoEditor for tabbed and flow content editing.

tasks:
  - id: tabbed-editor
    type: tabbedMonacoEditor
    properties:
      tabs:
        - name: JavaScript Code
          content: |
            function helloWorld() {
              console.log("Hello, World!");
            }
        - name: YAML Configuration
          content: |
            version: '1.0'
            services:
              app:
                image: my-app:latest
                ports:
                  - "8080:80"
      language: javascript
      theme: vs-dark

  - id: flow-editor
    type: flowMonacoEditor
    properties:
      flowContent: |
        name: Sample Flow
        description: This is a sample flow for testing.
      language: yaml
      theme: vs-dark
This example demonstrates how users can utilize the new components to manage multiple code snippets and flow content effectively. The functionality has been tested to ensure that switching between tabs and editing flow content works as expected.

### Setup Instructions

To set up the necessary resources for testing this PR, please follow the instructions below:

Ensure you have the latest version of the Monaco Editor library installed in your project.
Import the new TabbedMonacoEditor and FlowMonacoEditor components into your application.
Use the provided example flow code to test the new features in your local environment.

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
Hey @Manpreets59, was this PR removed by mistake? I still haven't had the time to check it out, but it should happen soon, if it's still relevant.

**Comment by Manpreets59** [comment]
Yes sir it was removed by mistake because I have deleted the clone repository of kestra in my local folder

**Comment by MilosPaunovic** [comment]
Okay, no worries. Do you want to re-open it again?

**Comment by Manpreets59** [comment]
Yes sir I want to work on it but due to my university exams I was not able to allocate the appropriate time to this issue. So if someone wants to work on this let them do so and if this issue is not closed I will work on this after the week.

**Comment by MilosPaunovic** [comment]
Okay, understood, no worries at all. Good luck with your exams! 🏆

**Pull request closed without merging**
