### PR TITLE
chore: upgrade to Micronaut 4.3.8

### LINKED ISSUE #1683: Since Micronaut Security 4.6.8 route match is randomly null in the SecurityFilter
### Expected Behavior

Migrating to 4.3.4 to 4.3.7 should not change the behavior of the Micronaut SecurityFilter.

### Actual Behaviour

After migrating from 4.3.4 to 4.3.7, we started to see randomly routeMatch request attribute being null in the Micronaut SecurityFilter.

This has been seen using a debugger, see the following screenshot that show that routeMatch is null for a request `GET /api.v1/demo/config` but this endpoint is defined in our application so there should be a route match.

Dowgrading to 4.3.4 fixes the issue.

route-match-issue

### Steps To Reproduce

_No response_

### Environment Information

Java 17
Linux

### Example Application

_No response_

### Version

4.3.7

### LINKED ISSUE #3553: Authorization header not forwarded when using Eureka Service Discovery
### Steps to Reproduce

1. Running the Eureka Server
2. Running a Micronaut service (token propagation is setup)
3. Running A Spring Boot service/Micronaut service
4. Running an Auth Server that is generating bearer tokens.

### Expected Behaviour
When service A (Micronaut service) makes a request to service B (Spring boot or Micronaut Service) the Token TokenPropagationHttpClientFilter successfully adds the Authorization Header and forward the request to service B using eureka discovery. When request arrives at service B the Authorization header is present.

### Actual Behaviour
When service A (Micronaut service) makes a request to service B (Spring boot or Micronaut Service) the Token TokenPropagationHttpClientFilter successfully adds the Authorization Header and forward the request to service B using eureka discovery. When request arrives at service B the Authorization header is missing.

### Environment Information

- Operating System**: Windows
- Micronaut Version: 2.0.0.M3
- JDK Version: 12

### Example Application
Will post an example application here tomorrow, still putting it together

### LINKED ISSUE #3553: Unable to migrate to Micronaut 4.3.7
### Issue description

Migrating from Micronaut 4.3.4 to Micronaut 4.3.7 causes an issue on EE; see https://github.com/kestra-io/kestra-ee/issues/1085

The root cause is that the routeMatch is now randomly null which causes issues in our security filter that will filter those requests and send 404 status.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes micronaut-projects/micronaut-core#3553

Using the trick explained [here](https://github.com/micronaut-projects/micronaut-security/issues/1683) to use a different cookie encoder to fix https://github.com/micronaut-projects/micronaut-security/issues/1683

### CODE REVIEW

**Comment by sdelamo** [comment]
does using `io.micronaut.http.cookie.DefaultServerCookieEncoder` fixes the null `RouteMatch` you were seeing?

**Comment by loicmathieu** [comment]
We still need to validate, it's not easily reproducible in local.
I'll update the Micronaut issue as soon as we know if it fixes the issue or not.

**Comment by loicmathieu** [comment]
@sdelamo we try it and it didn't fix the issue.

**Comment by tchiotludo** [comment]
@sdelamo, no the bugfix was release today and it's still happening.
We deploy and we still have unauthorized response. 
Even our demo is failing even with private navigation, just do on https://demo.kestra.io and you will see unauthorized response on refresh really easily. 
So, since even on private navigation it's still failing, the cookie don't seems to be the main reason. 
If you have anything we can share to help, but I'm not able to create a simple reproducer, just 100% reproduced on the deployed / env (and local) 
Doing a siege benchmark, we have 1 to 5% of the request failing

**Pull request merged**
