### PR TITLE
fix(ui): No more infinite loading on graph generation

### LINKED ISSUE #1284: Topology generation sometimes cause an infinite loading
### Expected Behavior

Self explaining

### Actual Behaviour

Sometimes when we write something on the editor, the topology generation causes an infinite loading

### Steps To Reproduce

Hard to reproduce unless adding a setTimeout in generateGraph()

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #1284

### CODE REVIEW

**Comment by Skraye** [comment]
Reproduce with your changes : 
* Create a new flow
* Add a task
* Add namespace and id -> infinite loading

**Review by Skraye — CHANGES_REQUESTED** [review]
Does not fix

**Comment by brian-mulier-p** [comment]
I think it's another one then cause I had several case where it was happening in an other way

**Comment by Skraye** [comment]
When reverting your change, I do not face the issue anymore.

Please provide a way to reproduce the initial issue so we can look further

**Comment by brian-mulier-p** [comment]
There is no reliable way to reproduce the issue, @tchiotludo already had the problem several times and it's happening when there is too much delay in validation API causing the graph to generate against a not validated yaml

**Comment by brian-mulier-p** [comment]
But I will look into the issue

**Comment by brian-mulier-p** [comment]
Standby due to lack of Low-Code QA, some behaviours have to be corrected before-hand (@Skraye is on it)

**Pull request closed without merging**
