### PR TITLE
Removed Inputs & Variables in "Edit Metadata" 

### PR DESCRIPTION
**Pull request by shabith16**
What changes are being made and why?

I have removed the MetadatInputs, MetadataVariables and their registrations in MetadataEditor. This changes has been done in order to remove inputs and variables field from the UI

### How the changes have been QAed?

I have not added any new features, But I ran the project multiple times in my local system to check its quality.

Pic of the UI:
Screenshot 2024-09-30 033445

### CODE REVIEW

**Comment by shabith16** [comment]
Hi, this will be my first contribution if merged. Have I pushed it correctly? Thank you.

**Comment by mounikaperi** [comment]
@shabith16 can you please help me in setting up the kestra run locally?
Or any instructions you can document?
I was able to setup docker desktop but facing some errors while running kestra locally. 
If possible can you please document how you have setup?
Thanks in advance!!

**Comment by MilosPaunovic** [comment]
@shabith16 Is this PR solving some of the issues from the list https://github.com/kestra-io/kestra/issues?

**Comment by shabith16** [comment]
@MilosPaunovic yes sir, it solves. I have removed the inputs and variables field from "flow metadata" as the issue addressed. 
Is there anything else, kindly point me it will be very helpful. 
Thanking you.

**Comment by shabith16** [comment]
@mounikaperi yes ma'am,
1. go to the ui folder and type the command "npm install"
2. command "touch .env.development.local"
3. add this api url to the file "VITE_APP_API_URL=http://localhost:8080"
4. then start the development server using "npm run dev"
5. now navigate to the root directory 
6. create docker-compose.yml file with the following content :
services:
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server local
    environment:
      KESTRA_CONFIGURATION: |
        micronaut:
          server:
            cors:
              enabled: true
              configurations:
                all:
                  allowedOrigins:
                    - http://localhost:5173
    ports:
      - "8080:8080"
7.run docker compose "docker-compose up"

**Comment by MilosPaunovic** [comment]
Hi @shabith16, I still don't get why have you removed those fields. Can you send me the link to the issue in question?

**Comment by MilosPaunovic** [comment]
@shabith16 I just figured out what the thing here is.

You've tried to amend https://github.com/kestra-io/kestra/issues/4868 with this PR, but it turns out that the original issue did not intend to completely remove those fields, but to prevent them disappearing after clicking on minus icon.

For that reason, I'll close this PR and you can open another one with the solution that is more suitable to the issue itself.

Anyway, thanks a lot for this attempt at contributing, it's really appreciated! 🚀

**Pull request closed without merging**
