### PR TITLE
fix(): display actions buttons on topology view

### LINKED ISSUE #2553: Missing actions buttons on Topology Only view
### Explain the bug

Topology view does not have the action button displayed anymore

This prevent from doing a flow from 100% low code on this view

image

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):

### PR DESCRIPTION
**Pull request by Skraye**
Buttons were only in the editor, so if it wasn't displayed, the actions weren't too.
To fix that, I made the bottom buttons a component used at the bottom of the "editorView" if the topology is displayed.

On other views than the topology, the buttons were hiding documentation or blueprints paginations, so it will be displayed inside the editor in those case

closes #2553

### CODE REVIEW

**Comment by brian-mulier-p** [comment]
image
image
buttons are not aligned vertically when switching view

**Review by anna-geller — APPROVED** [review]
LGTM 

image

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
See comments

**Comment by Skraye** [comment]
@brian-mulier-p 

> I wonder if the actions button should not have a background as it feels weird on the topology part 🤔
Already the case with top button

**Comment by brian-mulier-p** [comment]
> > Already the case with top button

What do you mean ? Top buttons are on a flat surface so it doesn't feel as weird as on the topology view with dots in background :thinking:

**Pull request merged**
