### PR TITLE
feat: support flow label values to be of data types different than string

### LINKED ISSUE #5707: Allow flow label values to be of data types different than strings (int, boolean, float)
### Feature description

Currently, trying to define booleans or integers as label values will not allow to save such a flow:

```yaml
labels:
  mynr: 42
  system.readOnly: true
```

You would need to wrap it in quotes:

```yaml
labels:
  mynr: "42"
  system.readOnly: "true"
```

This flow should ideally work:
```yaml
id: read_only
namespace: company.team

labels:
  mynr: 42
  system.readOnly: true

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

We want that everything that can be serialized as a string is allowed: int, float, str, bool.

Complex objects like lists or maps will still not be allowed as label values.

### PR DESCRIPTION
**Pull request by Malaydewangan09**
### What changes are being made and why?
Allow flow label values to accept data types such as int, float, and boolean, in addition to strings. Complex data types, such as lists and maps, remain unsupported as label values. This change improves label flexibility and serialization while maintaining simple data type compatibility.

closes #5707

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Hi,
Thanks for your contribution.
Could you please provide tests for that.
There are 3 existing tests for the various labels functionalities:
- LabelServiceTest
- RuntimeLabelTest
- ExecutionLabelsConditionTest

**Comment by Malaydewangan09** [comment]
Yes, I'll add the test cases.
Thanks!

**Comment by Malaydewangan09** [comment]
@loicmathieu 
Given that I modified the label deserializer,
Is it reasonable to include a test case such as this?

```
 @Test
void shouldHandleNonStringLabelValues() {
    Flow flow = Flow.builder()
        .labels(List.of(
            new Label("intLabel", "42"),
            new Label("boolLabel", "true"),
            new Label("floatLabel", "3.14"),
            new Label(Label.SYSTEM_PREFIX + "intSystemLabel", "100")
        ))
        .build();

    assertThat(labels, hasSize(3));
    assertThat(labels, hasItems(
        new Label("intLabel", "42"),
        new Label("boolLabel", "true"),
        new Label("floatLabel", "3.14")
    ));
```
Here that we are again passing strings only?

**Comment by loicmathieu** [comment]
@Malaydewangan09 I'm not sure your test do anything.
The best would be to:
1. update the RuntimeLabelTest to use a label with a primitive type.
2. Add a label to an existing flow in https://github.com/kestra-io/kestra/tree/develop/core/src/test/resources/flows/valids and either assert in an existing test that uses this flow or create a new test.

**Comment by Malaydewangan09** [comment]
Got it
Thanks!

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks for your contribution

**Pull request merged**
