### PR TITLE
add flatten

### PR DESCRIPTION
**Pull request by EdwardLi-coder**
feat(core):#2463

### CODE REVIEW

**Comment by Skraye** [comment]
Hi @EdwardLi-coder, thank you for your contribution! Could you add a test, please?

**Comment by EdwardLi-coder** [comment]
> Hi @EdwardLi-coder, thank you for your contribution! Could you add a test, please?

Sure.I will add a test.

**Comment by EdwardLi-coder** [comment]
Hello @Skraye,  I've added a test. Could you please review it? Thank you.

**Review by Skraye — APPROVED** [review]
LGTM, QA + code

**Pull request merged**
