### PR TITLE
feat/getting-started-editor

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes kestra-io/kestra-ee#518

### CODE REVIEW

**Review by anna-geller — APPROVED** [review]
LGTM 

image

**Review by Skraye — CHANGES_REQUESTED** [review]
Issue with readme
image

**Comment by brian-mulier-p** [comment]
No reproducer also from Yann on a fresh namespace, @anna-geller you want to give a look before the merge or can I merge ?

**Comment by anna-geller** [comment]
yup @brian-mulier-p checking now

**Review by anna-geller — CHANGES_REQUESTED** [review]
we'll build the extension locally tomorrow to check, for now we don't merge :)

**Review by anna-geller — APPROVED** [review]
now that the extension is published, everything works perfectly, see https://share.descript.com/view/kPVbzpB94Pz 

Great work!

**Pull request merged**
