### PR TITLE
fix(): handle flowable errors in allTasksWithChilds Flow method

### PR DESCRIPTION
**Pull request by Skraye**

### CODE REVIEW

**Review by loicmathieu — COMMENTED** [review]
There is no open issue nor any related test?

**Comment by Skraye** [comment]
@ No issue opened. I found this when working on subflow display in the topology. I didn't find any tests related to it, but it seems that some flows are not loaded anymore (flow that have error handling in their flowable)

**Comment by loicmathieu** [comment]
@Skraye when you didn't find any test ... the best is to add one.

**Comment by anna-geller** [comment]
is this PR still relevant @Skraye @loicmathieu? what blocks us from merging it during the cooldown?

**Comment by loicmathieu** [comment]
It misses a description of what it fixes and a test.

**Comment by Skraye** [comment]
Deprecated, was fixed differently since

**Pull request closed without merging**
