### PR TITLE
chore(ui): New design of tables within Executions and Flows pages Issue: #5586

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
**Closes Issue: #5586** 

image
image

> **Also Closes** https://github.com/kestra-io/kestra/issues/5861
image
image
image
image

### CODE REVIEW

**Comment by anna-geller** [comment]
@MilosPaunovic can this be merged?

**Comment by anna-geller** [comment]
@Skraye I think you already finished this, right? so it seems this can be closed?

sorry @Piyush-r-bhaskar in case we got it mixed with assignments

**Comment by Skraye** [comment]
#5586 has been done, not #5861 I believe, but a new PR would need to be open

**Comment by anna-geller** [comment]
@Piyush-r-bhaskar are you willing to open a new PR as @Skraye suggested? thanks in advance!

**Comment by Piyush-r-bhaskar** [comment]
> @Piyush-r-bhaskar are you willing to open a new PR as @Skraye suggested? thanks in advance!

Yes Sure @anna-geller . I will do it by EoD.

**Comment by MilosPaunovic** [comment]
So, just to confirm, @Skraye, can this PR be closed?

**Pull request closed without merging**
