### PR TITLE
fix/flow-triggers-without-condition

### LINKED ISSUE #2060: "Flows" trigger can't have null conditions
### Expected Behavior

_No response_

### Actual Behaviour

Following the rework on multiple conditions, having a Flow trigger with no conditions leads to a crash of the instance

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: 0.12.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #2060

### CODE REVIEW

**Comment by brian-mulier-p** [comment]
Just adding a flow with Flow trigger & no condition in flows/valid to load it in tests is enough to test it no longer breaks as it would fail all the other tests since it crashes the app at launch currently...

**Review by loicmathieu — COMMENTED** [review]
A Flow trigger without condition will never start any execution right? If so it may be a good idea to mandate a condition (but keep the code failsafe)

**Comment by brian-mulier-p** [comment]
It will always start (since no condition, it will start on every terminated (failed or success) flow)

**Review by loicmathieu — APPROVED** [review]
LGTM

**Pull request merged**
