### PR TITLE
fix(dashboard): persist logs when returning to Dash (#5251)

### LINKED ISSUE #5251: Dashboard logs disappear when returning to Dash
### Describe the issue

Preconditions: have any logs in place in dashboard
Step 1: Check logs on Dashboard
Step 2: Navigate to any other page for example "logs"
Step 3: Go back to Dashboard

Expected: logs shown
Actual: no logs - a refresh will fix it

https://github.com/user-attachments/assets/a0c0bc10-e27a-4874-a8b3-1c142166471d

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):

### PR DESCRIPTION
**Pull request by mithindev**
### What changes are being made and why?

This PR addresses issue #5251, where dashboard logs would disappear when returning to the Dash. The root cause was an issue in the date filtering logic, specifically how the time range was calculated in the `handleDatesUpdate` method. While the filters updated correctly when `startDate` and `endDate` were provided, the "30 days" time range calculation did not clearly include the current day.

**Fix:**
- **Start Date:** The logic was updated to subtract 30 days from today using `moment().subtract(30, 'days').startOf('day')`, ensuring the correct time range is captured.
- **End Date:** The end date now includes tomorrow's end of day using `moment().add(1, 'days').endOf('day')` to include today's data and account for any future logs.

With these adjustments, the filters now behave as expected, and logs persist when returning to the Dashboard.

**Closes #5251.**

---

### How have the changes been QAed?

The fix was manually tested by navigating between various dashboard sections and returning to the Dashboard. After updating the date logic, logs remained visible across all time ranges. A video demonstrating the issue resolution is provided below:

https://github.com/user-attachments/assets/8601c5d9-294e-4e0e-a907-3795561225c4

---

### Setup Instructions

No special setup is required. The changes apply universally across environments where the Dash is used.

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
Hey @mithindev, same issue as this one https://github.com/kestra-io/kestra/pull/5502#issuecomment-2418760624

Could you try to investigate further about which parameters are being set as dates to the enpoint?

**Comment by mithindev** [comment]
Hello @MilosPaunovic,

Upon further investigation, I found that the dates are managed through two mechanisms: 1) route parameters and 2) Local Storage. The start date remains consistent when navigating back, but the end date changes. The end date is retrieved from `this.$route.query.endDate` if available; otherwise, it defaults to `undefined`, meaning no end date filter is applied unless explicitly provided. The start date defaults to 7 days prior if not set.

The issue likely stems from route query parameters not updating correctly when navigating back, causing the end date to fall back to an older value and potentially exclude today's logs.

```js
endDate() {
    if (this.$route.query.endDate) {
        return this.$route.query.endDate;
    }
    // return undefined;
    return this.$moment().endOf('day').toISOString(true);
},
```

This fixed the issue as well.

**Comment by mithindev** [comment]
Hello @MilosPaunovic,

Upon reviewing the date values in the HTTP requests sent to the backend API, I confirmed that both the `endDate` and `startDate` are correctly transmitted, even when navigating between pages. However, despite the presence of logs (specifically the last one) within the time range, they do not appear upon navigation. In contrast, when I set the fallback for the end date to the end of today, the logs persist.

I also discovered that the timestamps for the logs stored in the database are in UTC. This suggests that the issue arises from a mismatch between how dates are stored and retrieved, leading to a time zone discrepancy. The stored `endDate` is in UTC, while the browser interprets local time, which results in today's logs being excluded. Identifying this took nearly six hours! 😅

image

Correcting this resolved the issue.

**Comment by MilosPaunovic** [comment]
Closing this issue with https://github.com/kestra-io/kestra/pull/5502#issuecomment-2437835918 as note. Will be re-opened if necessary. Thanks for the efforts on this @mithindev, it's really appreciated! 🚀

**Pull request closed without merging**
