### PR TITLE
fix: background color of namespaces

### LINKED ISSUE #5526: Add a background color to each namespace within Namespaces overview page
### Feature description

Should be:

image

image

Currently is:

image

[internal figma link](https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=681-5355&t=x7cKh6nwfA4p61Q3-4)

### PR DESCRIPTION
**Pull request by abhishekkhairnar**
### What changes are being made and why?
made the background color transperant for namespaces

---

### How the changes have been QAed?
image
image

---

### Setup Instructions
not required

Closes https://github.com/kestra-io/kestra/issues/5526.

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀

**Comment by MilosPaunovic** [comment]
This was great fix, thanks @abhishekkhairnar! 

Just one ask, if it's not too much trouble, could you use the [GitHub closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) to link to PR to the issue when you open your next one, it will make our life a bit easier?

P.S. I've added it in the description field for this one.

**Comment by abhishekkhairnar** [comment]
@MilosPaunovic 
thanks for compliment ❤️ and sure ill use the link to PR

**Comment by abhishekkhairnar** [comment]
@MilosPaunovic 
can you please tag someone here who is from backend i want little bit help to setup backend in my local so ill be able to contribute in backend also...

**Comment by MilosPaunovic** [comment]
For the backend contributions, it would be best if you first tried to set everything up by following guides from [this page](https://kestra.io/docs/getting-started/contributing), and if that does not work, then to ask questions on `#contributors` channel on our Slack.

**Pull request merged**
