### PR TITLE
feat(core): allow to configure min log level for tasks and triggers

### LINKED ISSUE #2245: Add `logLevel` Enum property on the core task
### Feature description

Hi,

Usually, all tasks are generating logs. These logs are collected by Kestra to be display in the UI. By default, this is the ideal behavior
But sometimes we don't want that logs are collected for example when we have

- huge log size (that use a lot of space in the Kestra DB for nothing and  that are not readable in Kestra UI)
- sensible information in the logs

So it would be interesting if we should be able to disable the collect of the log by Kestra.

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #2245

I wonder if this is the good implementation choice here and if we should not provide an instance-wide setting and re-evaluate our default to TRACE.

### CODE REVIEW

**Comment by anna-geller** [comment]
I'd suggest changing the property name to `logSeverityLevel` as it can be confusing what is the min and max level as here we limit the level being displayed to e.g. at most INFO so in theory it would need to be max level. Changing to severity level might be easier to grasp

**Comment by loicmathieu** [comment]
@anna-geller it's not the logLevel per se as it's the minimum level a log will be saved to the database. The log level on itself is set at logging time (in the Log task or in any task that emit a log), and there is also a log level filter on the UI so I wanted to make it clear that it's something different. This setting is often called the minLevel in log framework that have such settings hence the name here.

**Comment by loicmathieu** [comment]
@anna-geller I can reproduce the issue with your reproducer, it's because your flow has an underscore in it (each_parent) which is transformed to an hyphen inside the storage URI for an unknown reason (each-parent).
I'll have a look.

**Comment by anna-geller** [comment]
the comment landed on the wrong PR but roger that 👍

**Review by tchiotludo — CHANGES_REQUESTED** [review]
Why do you send the logLevel to taskRun, seems that we only need to have this at the Task level only?

**Comment by loicmathieu** [comment]
@tchiotludo 
> Why do you send the logLevel to taskRun, seems that we only need to have this at the Task level only?

Because when initializing the logger in the runContext there is a code path where you only pass a taskRun, I'll update to also pass the task as we have it and remove the logLevel from the taskrun.

**Comment by loicmathieu** [comment]
@tchiotludo I made the change your requested.

**Pull request merged**
