### PR TITLE
Align the pie chart labels when there are many states to display #5578

### LINKED ISSUE #5578: Align the pie chart labels when there are many states to display
### Describe the issue

When there are too many state labels to display, the donut chart labels take too much space
image

We should adjust the font to fit all states within the regular size of the chart

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

### LINKED ISSUE #6319: Overflow of states in the Donut chart on the main Dashboard
### Describe the issue

You can reproduce e.g. in Cloud 
image

### Environment

- Kestra Version: latest

### PR DESCRIPTION
**Pull request by DVUN716**
I solved that Align the pie chart labels when there are many states to display #5578

If there are too many main labels to display, the donut chart label takes too much space. That's why I only marked at least 4 main labels, and modified the remaining labels to appear and omit through the button.

Press the blue + View More button to display all labels. The button is visible when there are more than 5 labels.
And when all the labels are showing, press the red - View Less button to see only four labels again.
View More
View less

Closed #5578
Closes https://github.com/kestra-io/kestra/issues/6319.

### CODE REVIEW

**Comment by DVUN716** [comment]
@MilosPaunovic May I know how long it's been going on?

**Comment by MilosPaunovic** [comment]
Not sure I get the question there?

**Comment by DVUN716** [comment]
After writing pr and you're in charge of the developer, it's not merging.
I want to know what's wrong with my code, if I'm still reviewing it, and if I'm still reviewing it, I want to know how much it is, and when the merge will be.

**Comment by MilosPaunovic** [comment]
It will be merged when I get the chance to review it. And that will happen probably some time next week.

**Comment by DVUN716** [comment]
I see. Thanks.

**Comment by MilosPaunovic** [comment]
Hey @DVUN716, I've just got some time to review this properly. Could you please try to resolve conflicts with `develop` branch first, so I can give it a look? Although it seems quite nice on the screenshots.

**Review by MilosPaunovic — APPROVED** [review]

**Comment by MilosPaunovic** [comment]
Thanks for this contribution @DVUN716! 🚀

**Pull request merged**
