### PR TITLE
Fix(UI) dashboard filter remove default

### PR DESCRIPTION
**Pull request by satvik2131**
fixed default date filter not removing in dashboard 

https://github.com/user-attachments/assets/ee418184-46bd-45bc-a03b-bfded698092d

### CODE REVIEW

**Review by Piyush-r-bhaskar — COMMENTED** [review]
https://github.com/user-attachments/assets/31b4bef7-296a-4787-b764-3c3f4c8f8a4e

Backspace is removing the default one _but also removing manually added filters two at a time._

**Comment by satvik2131** [comment]
> Backspace is removing the default one _but also removing manually added filters two at a time._

okay , got it will fix it .

**Comment by satvik2131** [comment]
@Piyush-r-bhaskar , please check the latest changes I made .

**Review by Piyush-r-bhaskar — APPROVED** [review]
Looks good but I think it would be better if we could also remove clicking on cross icon and keep`@remove-tag` @satvik2131 

Let's wait for @MilosPaunovic review now.

**Comment by Piyush-r-bhaskar** [comment]
> @Piyush-r-bhaskar , please check the latest changes I made .

@satvik2131  I checked it again & filters we able to remove on clicking close but it's not happening now after `@remove-tag` removal.

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
As @Piyush-r-bhaskar, now the filters aren't removable by clicking on the `x` icon at the right side.

**Comment by satvik2131** [comment]
ok , will fix that .

**Comment by MilosPaunovic** [comment]
Closing this for now, @satvik2131 if you implement what's missing, we can reopen this PR or you can open a fresh one.

**Pull request closed without merging**
