### PR TITLE
Update Monaco Editor & YAML

### PR DESCRIPTION
**Pull request by tchiotludo**

### CODE REVIEW

**Comment by tchiotludo** [comment]
@yuri1969 still have the issue : 

image
Autocompletion still give me all the props from all plugins, but i've tested with only updating the monaco editor (not monaco-yaml) it's seems to works fine !

**Comment by yuri1969** [comment]
@tchiotludo Nice

**Comment by tchiotludo** [comment]
I've updated monaco [here](https://github.com/kestra-io/kestra/commit/8bff0beed92339d51262e9518e8ce42133f9348c), tell me how it's going please

**Comment by yuri1969** [comment]
The syntax highlighting seems to work as intended.

**Pull request closed without merging**
