### PR TITLE
Added scroll to the tree view

### PR DESCRIPTION
**Pull request by Niravdas**
- Added scroll to the tree view
- Made it responsive with media query
- Modified scroll bar height to make it look attractive

### CODE REVIEW

**Comment by Niravdas** [comment]
The small screen having scrollbar.

image


On larger screen removed scroll due to responsiveness.
Screenshot 2024-10-24 223429

**Comment by MilosPaunovic** [comment]
I haven't seen @Skraye self-requested a review here, so I'll just leave this note I've already found and be happy to give it over for a final review and merging 😄 

So, when there is a scrollbar, the highlight color of the selected line with the file/folder does not go all the way to the end. Could you see and amend that @Niravdas?
image

**Comment by Niravdas** [comment]
Thanks for the feedback, I am looking into this.

**Comment by Niravdas** [comment]
@MilosPaunovic ,
I am unable to re-produce issue with file name,
I tried it with dark theme and adding JS file too.

Is there any specific steps which can help me re-produce the issue?

image

image

**Comment by MilosPaunovic** [comment]
Just click on the last file, to open it. It will change background color.

**Comment by Niravdas** [comment]
@MilosPaunovic 
Thanks for feedback, it is resolved now.

**Comment by Skraye** [comment]
@MilosPaunovic has you have started, I'll let you finish this one (given that is also only frontend)

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
When we have deeply nested files, it seems like the sidebar is being expanded to maximum available value and we lose the ability to resize it. We should not lose that ability nor the width of sidebar should be changed. Can you check that @Niravdas?

[Screencast from 2024-11-15 14-26-50.webm](https://github.com/user-attachments/assets/8a8558f7-8ada-4382-92f2-29e90c4083f2)

**Comment by MilosPaunovic** [comment]
Hey @Niravdas,

I've tried to make this work by going by your path, but it's not ideal.

Will have to close this PR, if you decide to try another approach, feel free to do it. And, if you're willing to try something else, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

Thanks for your efforts here! 🚀

**Pull request closed without merging**
