### PR TITLE
feat(ui): Allow user to display specific columns only in executions list

### LINKED ISSUE #566: Allow customization of columns displayed in the Executions data table
For now, the list of columns displayed on every data table are fixed.
We need to allow customization of columns visible and maybe add some that can be useful (for example inputs for execution).

### PR DESCRIPTION
**Pull request by Skraye**
This PR add:

* Some new columns like: Inputs, Task Id (last executed or being executed) and its number attempt, and the flow revision. 
* The possibility to chose which columns should be displayed. I've set the ID as mandatory, but I suggest that the state should be too (because an execution without his state makes no sense ??)

I guess some CSS could be also improved like the revision display. (the selection isn't very beautiful but it linked to Element Plus and the global theme of the app)

Here's a screenshot, there is also a tooltip on the task id to precise its the last executed and its number attempt.
image

close #566

### CODE REVIEW

**Comment by anna-geller** [comment]
awesome work, @Skraye! some issues worth addressing:  

1. When going to Executions, I see an empty table at first 
image

afterwards the table looks fine, only for the first time, we need to prefill the Select field with those fields that are displayed by default

image

2. The id filed cannot be unselected so it shouldn't be listed in the select field
3. Is there a way to remove the (1) next to the task ID? it's probably not a bug, but as end user this looks like a bug

Apart from that really nice, even a long list of inputs looks very well:

image

**Review by anna-geller — CHANGES_REQUESTED** [review]
see other comment

**Comment by Skraye** [comment]
@anna-geller The number next to the task Id is the attempt number. Do you have a suggestion for a better way to display it ?

**Comment by yuri1969** [comment]
@Skraye IMO UI should not render the attempt number just for the 1st attempt. The reasoning is:

- the 1st attempt is implicit
- the 2nd and following attempts bear the important information (there are retries)
- free some view space

---

My feedback concerns options displayed in the column chooser in the `flows/edit/<namespace>/<flowId>/executions` view - the chooser should not present `flowId` & `namespace` options since these have no effect there.

**Comment by brian-mulier-p** [comment]
at first glance, I would say it would look better to have a display name for the select options with the first letter being uppercase

**Comment by Skraye** [comment]
@yuri1969 Totally makes sense, and what do you think of the number in parentheses? Is it explicit enough? 

I missed the execution list, I will try to handle this properly as they are two pages with different needs but using the same components  

@brian-mulier-p I Just forgot to add `$t`, fixed :+1:

**Comment by yuri1969** [comment]
> @yuri1969 Totally makes sense, and what do you think of the number in parentheses? Is it explicit enough?

No UX person here, but it seems it is.

The `taskId` & `attempt` combination should help to identify impaired _RUNNING_ executions (retrying - attempt > 1) and logically group them by failing task.

**Comment by anna-geller** [comment]
@Skraye, something is weird - I selected the last 1 hour, and there are executions to display but the table is empty - can you cross-check?

**Review by anna-geller — APPROVED** [review]
👌

image

**Pull request merged**
