### PR TITLE
fix: set the webhook key in the controller

### PR DESCRIPTION
**Pull request by loicmathieu**
close [#1826](https://github.com/kestra-io/kestra/issues/1826)

### CODE REVIEW

**Review by tchiotludo — CHANGES_REQUESTED** [review]
Seems too hacky, before it was working without this hack, why not now?

**Comment by loicmathieu** [comment]
Because before, flows were only sent in JSON, now that we send them in YAML and parse the YAML, the key is reset on update as the update parses the YAML and overrides the JSON.
So we cannot do anything at the task level.

Another solution would be to mandate a key to be set y the user; this is less convenient for sure but avoid any hack.

**Comment by tchiotludo** [comment]
mandate the key is a breaking change.
What I don't understand, we used to source to to generate an object, at this time the key must be created, why it's not keep back ?

**Comment by tchiotludo** [comment]
close in favor of https://github.com/kestra-io/kestra/commit/5b568ad9ba9295dcaa0d7f965809ba74550e9011

**Pull request closed without merging**
