### PR TITLE
feat(ui) Left Menu in Mobile

### LINKED ISSUE #1425: Left menu on mobile
Left menu on mobile should be forced reduced at least, or even more hidden by default

### PR DESCRIPTION
**Pull request by MRADUL9936**
Relates to https://github.com/kestra-io/kestra/issues/1425.

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
Hi @MRADUL9936,

This can't be merged yet.

First thing, in mobile view, if you expand menu, there is no option to collapse it anymore.
Also, you've mentioned the hamburger menu in the issue and got a green light for it, but I do not see anything like that so far.

**Comment by MRADUL9936** [comment]
OUTPUT :


Uploading LeftMenuInMobile.mp4…

**Comment by MRADUL9936** [comment]
@MilosPaunovic   
I believe the recent changes made in the pull request have resolved the issue discussed. I appreciate your feedback and have implemented the necessary adjustments. Please review at your convenience.
OUTPUT :

https://github.com/user-attachments/assets/1577c2c0-23a8-4064-bb57-2fb6d470ed35

**Comment by MilosPaunovic** [comment]
The top header button now seems quite weird.

I can not merge this one, our designer needs to have a look at it first, but I believe we'll go with whole other approach.

Thanks for the efforts for this one and for all the others @MRADUL9936! 🚀

**Pull request closed without merging**
