### PR TITLE
fix(run): add LD_PRELOAD to handle duckdb/rocksdb libc conflict

### PR DESCRIPTION
**Pull request by fhussonnois**
related-to: kestra-io/plugin-jdbc#165

### CODE REVIEW

**Comment by fhussonnois** [comment]
FYI: @Ben8t

**Comment by Ben8t** [comment]
Ahah @fhussonnois it was as simple as this 😮 !? Can it be added to bugfix release 😇  ?

**Comment by tchiotludo** [comment]
@fhussonnois do windows is also impacted ?

**Review by loicmathieu — CHANGES_REQUESTED** [review]
We already discussed that and it's dangerous to play with this system environment.
Things are moving on at RocksDB side, we should have a fix at some point (in fact, it may be already available) so better to wait for it.

**Comment by tchiotludo** [comment]
@loicmathieu we can't wait anymore, even if there is a fix, we are not sure about the release date. So I will pick-up the hack that is very low in term of conflict for our customer (since it's inside a docker container) 
@fhussonnois maybe add an env vars to disable this behavior in case of ?

**Comment by fhussonnois** [comment]
Env var `LD_PRELOAD_ENABLED` was added. This var can be set to `false` to disabled the preload. I really think we should be cautious with that fix. But, we could merge it and see how it goes. If a fix is provided by the RocksDB team before the next release we could still revert it.

**Pull request merged**
