### PR TITLE
fix(ui):All popup windows now use markdown — some confirmation dialogs need adjustments

### LINKED ISSUE #5981: All popup windows now use markdown — some confirmation dialogs need adjustments
### Describe the issue

Followup to https://github.com/kestra-io/kestra/issues/5814#issuecomment-2477174652
image

Demo https://share.descript.com/view/UanOyAPuOj1

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by pphy03**
### What changes are being made and why?

---

### How the changes have been QAed?

---

### Setup Instructions

Close #5981

### CODE REVIEW

**Comment by Piyush-r-bhaskar** [comment]
@MilosPaunovic May I ask for chance to review this at first step ?

**Comment by MilosPaunovic** [comment]
Absolutely, that would be of great help, but this PR might be tricky as we want to go with a bit different approach, something like https://github.com/kestra-io/kestra/pull/5933.

May I suggest that, if you're willing to do PR reviews, try to check these ones: https://github.com/kestra-io/kestra/pull/6224, https://github.com/kestra-io/kestra/pull/6062, https://github.com/kestra-io/kestra/pull/6213? just bare in mind I would also have to review them before merging, it would not be anything related to your review being not alright or anything, it's just our process.

**Comment by Piyush-r-bhaskar** [comment]
> Absolutely, that would be of great help, but this PR might be tricky as we want to go with a bit different approach, something like #5933.
> 
> May I suggest that, if you're willing to do PR reviews, try to check these ones: #6224, #6062, #6213? just bare in mind I would also have to review them before merging, it would not be anything related to your review being not alright or anything, it's just our process.

Perfect...Thank You @MilosPaunovic

**Comment by Piyush-r-bhaskar** [comment]
Just for your info. & to get suggestions: @MilosPaunovic @anna-geller 

> [!NOTE]
> If you see the JSON, the “force run confirm”: has content which includes `<br>, <code>, <ul>, <li>` tag for the work it does. But since the tags are being stripped, adding them in JSON won’t serve any purpose and as you can see from screenshot below, @pphy03 code has not entertained the tags as expected. 

image
looks hard-coded
image

**It should be something like this as per currently being used _`ElMessageBox`_**

image
image

> [!TIP]
> **To implement something like below: `ElDialog` would be an option**

image

**Which is currently being used for `Set Labels and Change State` of Executions**

image
image

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀 

You were on a good track here @pphy03, but I had to amend the approach a bit to align with some previous work on similar topic. Anyway, thanks a lot for the efforts here! 🚀 

Thanks to you, as well @Piyush-r-bhaskar!

**Pull request merged**
