### PR TITLE
implemented a new input type email with validation

### LINKED ISSUE #5477: Add support of input type EMAIL
### Feature description

Sometimes the input is not just plain string but email. Implementing email validation regex every time can be tedious — we can add a new EMAIL input type to help with that use case. 

```yaml
id: myflow
namespace: company.team
inputs:
  - id: myemail
    type: EMAIL
    defaults: hello@kestra.io
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.myemail }}
```

trying to enter sth like "Arbitrary string" would not be allowed as this input must be a valid email.

### PR DESCRIPTION
**Pull request by hashimzs**
### What changes are being made and why?

closes #5477
A new input type of email has been added to speed the process of making email inputs with the required regex pattern
---

### How the changes have been QAed?

The changes have been tested by creating a new flow with an input of type email. Furthermore the flow has been executed with a valid email and an invalid email

```yaml
id: myflow
namespace: company.team
inputs:
  - id: myemail
    type: EMAIL
    defaults: hello@kestra.io
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

```

---

### Setup Instructions

No additional setup is required.

### CODE REVIEW

**Review by Skraye — APPROVED** [review]
Perfect! Thank for your contribution!

I will merge it once the CI is green!

**Comment by hashimzs** [comment]
@Skraye one of the workflows is failing is it an issue that can be fixed on my part or?

**Comment by Skraye** [comment]
@hashimzs A test that need to be updated :
```
 io.kestra.webserver.controllers.api.PluginControllerTest ✘ inputs()

    java.lang.AssertionError: 
    Expected: is <17>
         but: was <18>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.kestra.webserver.controllers.api.PluginControllerTest.lambda$inputs$13(PluginControllerTest.java:216)
        at io.kestra.core.Helpers.runApplicationContext(Helpers.java:83)
        at io.kestra.webserver.controllers.api.PluginControllerTest.inputs(PluginControllerTest.java:209)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by hashimzs** [comment]
@Skraye i have updated the test that was failing

**Comment by hashimzs** [comment]
@Skraye the workflows are still failing can you give me some pointers

**Comment by Skraye** [comment]
I don't think its related to your changes but more an issue from the CI as other workflow are having the same issue
Don't worry, from now I'll make sure this one is merged!

**Pull request merged**
