### PR TITLE
bug(ui): This fix will correctly updates the pebble expression when output…

### LINKED ISSUE #5842: [Regression] Outputs tab now displays incorrect Pebble expressions and Pebble is rendered in the wrong place
### Describe the issue

image

Demo: https://share.descript.com/view/O9XWH3nGBHZ

To reproduce, run this flow and navigate to Outputs:

```yaml
id: hello-world
namespace: repro

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
```

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by ManojTauro**
… tab is rendered

### What changes are being made and why?

Closes #5842.

Update the pebble expression when the `Outputs` page is rendered. Also, when user clicks on the `Debug Outputs` button on the `Outputs` page, display correct value below the `Debug Outputs` block.

This issue occurred because of `JSON.parse()` method failing when result from the server is simple text instead of JSON.

---

### CODE REVIEW

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀

**Comment by MilosPaunovic** [comment]
@ManojTauro Before the merge, can you just handle the disappearing value note from the image in the description of the original issue, to cover everything mentioned there?

**Comment by ManojTauro** [comment]
@MilosPaunovic I just wanted to clarify that the value should disappear when we click the `Debug Outputs` button and it should be visible when the page is rendered initially.

**Comment by MilosPaunovic** [comment]
I would say that it should be shown at all times except when the `Debug outputs` button is clicked with the rendering expression is the same as the one we're showing as value.

**Comment by ManojTauro** [comment]
Hi @MilosPaunovic, I'm sorry. I'm not able to understand what is expected. Could you please give me an example? This will help me understand it better.

Thanks

**Comment by MilosPaunovic** [comment]
Yeah, no worries.

So, if we use this flow as the example:
```
id: output_pebbles
namespace: github.review

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
```

And if we have this `{{ outputs.first_task["value"] }}` in the `Debug Expression` section, when we click on the `Debug Outputs` button, we'll have that value in the section, and, if we have that `outputs -> first task -> value` selected in cascader, the same `thrilled` value is going to show up in the section below.

So, in the case we're debugging and showing same thing, hide the value below.

image

**Comment by ManojTauro** [comment]
Thanks @MilosPaunovic. I understand it now.

I plan to modify the code as shown below. I added a v-if to check `selectedValue` and `debugExpression`.
`<VarValue v-if="selectedValue !== debugExpression" :value="selectedValue" :execution="execution" />`.

I'll commit this change in some time.

**Review by MilosPaunovic — APPROVED** [review]

**Pull request merged**
