### PR TITLE
Feat/location by tenant

### PR DESCRIPTION
**Pull request by loicmathieu**
Allow configuring the internal storage at the tenant level.

The local storage has been updated to allow defining a different base path per tenant.

### CODE REVIEW

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Lacks a StorageTestSuite new test to cover that we now allow tenant-specific storage location (will help for other implementations).
Otherwise LGTM

**Comment by loicmathieu** [comment]
@brian-mulier-p testing it from OSS can be hard because we always return an empty location from OSS and moreover testing that it uses different location is a per-storage validation (different base path, different bucket, ...).

The only thing I can think of is to spy the TenantService to check that it has been correctly called but, honestly, it has no real benefit. 

I think this is again something that should be tested at a higher level (as we need to do for the tenant anyway)

**Comment by anna-geller** [comment]
this isn't merged yet as it seems we weren't fully aligned on the specific implementation

@loicmathieu perhaps you can close the PR and we can plan a new implementation in 0.15.0? if it is easier to build on top of this PR, maybe we can switch to a draft status?

**Comment by loicmathieu** [comment]
We plan a more broad implementation for 0.20

**Pull request closed without merging**
