### PR TITLE
feat(*): update execution labels

### LINKED ISSUE #2633: Allow setting custom Execution labels from the Executions page
### Feature description

Related to https://github.com/kestra-io/kestra/issues/2632 

Often, users want to set labels after the fact (e.g. after analyzing an already completed execution). Labels can then be used to: 
- mark failed Executions as "Resolved" after investigating the reason for failure
- set custom labels based on some outcome/output of that Execution 

## Possible usage

Select one or more executions and click on "Set labels":

image

Then, it can pop up similar input fields as here with key-value pair(s) to enter:
image

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes #2633

Allow to set (add and update) execution labels for terminated executions.

image

Also provide bulk action for that.

image

### CODE REVIEW

**Comment by yuri1969** [comment]
Big thanks for implementing this feature!

I have two questions:
1. Is there a chance to include also the `PAUSED` state on top of the terminated state(s)? I haven't checked the implementation, but the main use case is commenting on executions waiting on a manual resume action (providing business context - _"note: Do not resume until go-live"_).
2. Appending new labels is definitely useful, but updating the set of existing labels by a chain of _get->modify->persist_ actions would provide full control, wouldn't it? Are there technical limitations/implications? The use case: An execution fails. Add a `note` label describing the failure reason. Fix the issue & resume the execution. Remove the `note` label. This way it is possible to check/filter _unattended_ failed executions with no label `note`.

**Comment by loicmathieu** [comment]
Hi @yuri1969 

> Is there a chance to include also the PAUSED state on top of the terminated state(s)? 

No as PAUSED is a transient state so there is a risk of races. During an execution of a flow, the execution can only be updated by the executor not directly on the database or its update can be overridden by the executor.

> Appending new labels is definitely useful, but updating the set of existing labels 

We can easily handle updating existing label, I'll do the modification to support them. For deleting existing one I need to have a look to see if it's possible or not. Moreover some labels comes from the flow so if we allow deleting them the resulting labels could be no more aligned with the flow labels.

**Comment by yuri1969** [comment]
@loicmathieu 
> some labels comes from the flow so if we allow deleting them the resulting labels could be no more aligned with the flow labels.

You are right - copied flow labels should remain immutable.

We could finalize the label change action with applying flow labels as we do at execution start. Although, this behavior might be a bit odd/unexpected.

**Review by Skraye — APPROVED** [review]
LGTM

**Pull request merged**
