### PR TITLE
Improve doc

### LINKED ISSUE #970: Flow schema validation issue with multiple conditions
### Expected Behavior

_No response_

### Actual Behaviour

When using multiple conditions, the flow schema validator shows some warning but the flow works without issue.

Capture d’écran du 2023-02-09 17-21-35

### Steps To Reproduce

You can use the example multiple condition flow, it triggers the issue:

```yaml
id: trigger-multiplecondition-listener
namespace: io.kestra.tests

tasks:
  - id: onlyListener
    type: io.kestra.core.tasks.debugs.Return
    format: "let's go "

triggers:
  - id: multipleListenFlow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-a
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-b
```

### Environment Information

- Kestra Version: 0.6.1-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Linux
- Java Version (If not docker): 17

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by loicmathieu**
Multiple doc improvements:

- Don't transform `@JsonType` as they procudes stange documentation like https://kestra.io/plugins/plugin-gcp/tasks/bigquery/io.kestra.plugin.gcp.bigquery.Copy.html#retryauto
- Add missing `@PluginProperty` on trigers
- Add a `@Schema(defaultValue="...")` on the WebHook trigger to mask the generated ID from the documentation
- Don't register plugin classes that have the `@Hidden` annotation, this annotation is also added to the `Template$ExecutorTemplate` class.
- Enable MAP_VALUES_AS_ADDITIONAL_PROPERTIES  so that for Map properties, the value type is automatically registered as additionalProperties inside the JSON Schema.

Fixes #970

### CODE REVIEW

**Comment by loicmathieu** [comment]
@tchiotludo the PR is ready to review.

Due to not transformaing `@JsonTypeInfo` anymore, definitions like `io.kestra.core.models.tasks.Task-2`, `            io.kestra.core.tasks.scripts.Bash-1` and `io.kestra.core.tasks.scripts.Python-1` are gone, replaces by the non-suffixed versions. I hope nothing relies on these to exist.

**Comment by tchiotludo** [comment]
@loicmathieu : we have this [here](https://github.com/kestra-io/kestra/blob/1d6a214f520266aae3da21ac44bcc51bc1b02edb/core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java#L109) only as I know. You have handle it.

**Comment by loicmathieu** [comment]
>@loicmathieu : we have this [here](https://github.com/kestra-io/kestra/blob/1d6a214f520266aae3da21ac44bcc51bc1b02edb/core/src/main/java/io/kestra/core/docs/JsonSchemaGenerator.java#L109) only as I know. You have handle it?

@tchiotludo yes, this part should not be needed anymore and I removed it. I manually verify task validation througth the UI and it works (and it fixes the multiple-condition validation)

**Comment by loicmathieu** [comment]
I checked the validation on the UI and this PR may break something there.

Example for this invalid flow (not existing task):
```yaml
id: toto
namespace: io.kestra.test
tasks:
  - id: titi
    type: io.kestra.plugins.class.MyPlugin
```

Previously the error was
image

And now it's 
image

**Comment by loicmathieu** [comment]
@tchiotludo in fact this error is also in master so nothing is changed in this PR regarding the flow validation.

**Pull request merged**
