### PR TITLE
feat(core): rename the Flow task to Subflow

### PR DESCRIPTION
**Pull request by loicmathieu**
Fixes [#2604](https://github.com/kestra-io/kestra/issues/2604)

### CODE REVIEW

**Review by anna-geller — APPROVED** [review]
works!

image

image

image

**Review by brian-mulier-p — CHANGES_REQUESTED** [review]
Please update tests to all use the new Subflow named task instead of Flow everywhere it is specified (using CTRL SHIFT F)
image

**Comment by brian-mulier-p** [comment]
@loicmathieu I added [this PR](https://github.com/kestra-io/ui-libs/pull/9) needed for subflow expand to work properly as it was missing :+1:

**Review by brian-mulier-p — APPROVED** [review]
LGTM

**Pull request merged**
