### PR TITLE
fix: flow trigger docs

### PR DESCRIPTION
**Pull request by anna-geller**

### CODE REVIEW

**Comment by anna-geller** [comment]
@fhussonnois do you remember how you made the flow outputs available to downstream flows via `{{ trigger.outputs.flow_output_id }}`? this should work but currently tests fail when using this syntax, could you check and fix my branch so we can merge the fix to the Flow trigger docs + tests?

**Comment by fhussonnois** [comment]
The expression `{{ trigger.outputs.flow_output_id }}` is correct, but you should not modify the flows under `test/resources/flows/valids`. We have assertions that can be based on task-id, return values, output names, etc. So, if you update the flows, we have also to rewrite the tests

**Comment by anna-geller** [comment]
Got it, can you help by fixing the tests and adjusting the flow and pushing to this branch? Long term, we want to deprecate the option to access outputs of upstream flows by using `{{ outputs.task_id_output_name }}` as it's dangerous in terms of permissions (using outputs not exposed via flow outputs) + confusing (this syntax is for the current flow only)

**Comment by anna-geller** [comment]
anyway, I'll let you fix the outdated tests whenever you want 👍 for now, PR to fix docs https://github.com/kestra-io/kestra/pull/5592

**Pull request closed without merging**
