### PR TITLE
fix(core): add implemntation for md5, sha1, and sha512 filters (#5436)

### LINKED ISSUE #5436: Editor documentation lists non-existant Pebble filters
### Describe the issue

The documentation that shows up in the sidebar in the flow editor shows some filters that don't seem to exist - trying to use them fails like below:
```
2024-10-13 04:24:21.979

io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
2024-10-13 04:24:21.979

io.kestra.core.exceptions.IllegalVariableEvaluationException: io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
    at io.kestra.core.runners.VariableRenderer.properPebbleException(VariableRenderer.java:64)
    at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:120)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:91)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:76)
    at io.kestra.core.runners.VariableRenderer.render(VariableRenderer.java:68)
    at io.kestra.core.runners.DefaultRunContext.render(DefaultRunContext.java:186)
    at io.kestra.plugin.core.log.Log.run(Log.java:80) at io.kestra.plugin.core.log.Log.run(Log.java:21)
    at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:76)
    at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
Caused by: io.pebbletemplates.pebble.error.PebbleException: Filter [md5] does not exist. (Hello World! {{ "FooBar" | md5 }}:1)
    at io.pebbletemplates.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:49)
    at io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
    at io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
    at io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
    at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
    at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:96)
    at io.kestra.core.runners.VariableRenderer.renderOnce(VariableRenderer.java:114) ... 8 more
```

I tested md5, sha1, and truncate and they fail - there's probably a few more in there.

### Environment

- Kestra Version: 0.19.2 - 4338437 Tue, Oct 8, 2024 9:52 AM
- Operating System (OS/Docker/Kubernetes): Docker (kestra/kestra:latest)
- Java Version (if you don't run kestra in Docker):

### PR DESCRIPTION
**Pull request by SayedQassim**
### What changes are being made and why?

closes #5436 
added implementation for md5, sha1, sha512 filters as they were documented but not implemented and when using them it produce an error that the filter dose not exist.
---

### How the changes have been QAed?

---
tested using trying the filter by a simple workflow for all three algorithms 

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀 {{ "hello" | sha512 }}
```

### Setup Instructions

no further setup is required

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
Hi,
Thanks a lot for your PR.
As all 3 filters share most of their code, can you extract a parent abstract class to share the code?
Also, we need a test for each filter, ou can find an example here: https://github.com/kestra-io/kestra/blob/develop/core/src/test/java/io/kestra/core/runners/pebble/filters/EndsWithFilterTest.java

**Review by loicmathieu — CHANGES_REQUESTED** [review]
Some changes are needed before we can merge, I approve the PR by mistake.

**Comment by SayedQassim** [comment]
Hi @loicmathieu, I had this idea but I was not sure If I do implement it or not as a I was trying to follow the same style of the other filters in the codebase, I will work on refactoring them and adding the test cases.

**Comment by Skraye** [comment]
@loicmathieu @SayedQassim Any update on this?

**Comment by SayedQassim** [comment]
Hi @Skraye, Sorry for that, I got busy on project and did not have much time to work on the refactoring, I have talked to my colleague @hashimzs and his willing to contribute and close this PR if that ok with you, Thank you and sorry again.

**Comment by hashimzs** [comment]
@loicmathieu @Skraye i have implemented the required changes

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Pull request merged**
