### PR TITLE
disables running ci on draft pr, fixes 4964

### LINKED ISSUE #4964: Don't run CI on draft PR
### Issue description

To save some CI capacity, don't run CI on draft PR so we can use draft to create PR before we want to build them.

Something like that should work:
```
pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# on each job:
if: "github.event.pull_request.draft != true"
```

### PR DESCRIPTION
**Pull request by phoenix24**
### What changes are being made and why?
adds a flag to test for draft pr, and disable ci run. fixes #4964 

---

### How the changes have been QAed?
by testing against a draft pr.

---

### CODE REVIEW

**Comment by anna-geller** [comment]
is this finished? I see only whitespaces added, am I overlooking some commits?

**Review by anna-geller — APPROVED** [review]
nice! `if: github.event.pull_request.draft == false` LGTM

**Comment by phoenix24** [comment]
Hey @anna-geller, thank you for approving the pr. However I don't have the merge permissions, and someone from maintainers group might be able to help. Hey @loicmathieu - do advise.

**Comment by loicmathieu** [comment]
We are in the process to release 0.19. I'll check this end of the week.

**Comment by phoenix24** [comment]
Hey @loicmathieu hope you're doing well. I just wanted to bring this to your attention, thank you!

**Comment by loicmathieu** [comment]
@phoenix24 please see the instruction in the issue, what you did is not enough as when the PR will move from draft to ready for review the CI will not run.

**Pull request closed without merging**
