### PR TITLE
Concurrency limit should be greater than Zero

### LINKED ISSUE #4904: [UI] Concurrency allows negative values in the low-code editor
### Describe the issue

Edit flow - add concurency with negative values- it allows to be saved
https://github.com/user-attachments/assets/9000f400-cad2-4a30-9705-2149836e7cc1

### Environment

- Kestra Version: develop
- Operating System (Docker):

### PR DESCRIPTION
**Pull request by mounikaperi**
### What changes are being made and why?
closes #4904 https://github.com/kestra-io/kestra/issues/4904
The concurrency limit allows negative values to be set at UI causing one API call to reach to backend and fail the validation there.

We are restricting the user to enter negative values now in the UI level itself

The Minus sign of el-input-number component gets disabled once it reaches 1 

We are setting 1 as the minimum limit for concurrency as concurrency limit should be greater than 0

image

---

### How the changes have been QAed?

---

### CODE REVIEW

**Comment by Skraye** [comment]
Thanks for your PR! 
However as mentioned in the issue, we need to use the schema for setting this minimum
The component `TaskBasic.vue` is a very generic component, and so you can not set the minimum as 1 as for a lot of other use cases, this will not match with the need.

To help you, let me give you some tips : 
* First, note that the schema for the concurrency is fetch here : https://github.com/kestra-io/kestra/blob/develop/ui/src/components/flows/MetadataEditor.vue#L172
* Then, it's provided in the taskBasic here : https://github.com/kestra-io/kestra/blob/develop/ui/src/components/flows/MetadataEditor.vue#L117
* Also, if you look at what the schema looks like, you will notify this : 
image
* Finally, see that in taskBasic, you have access to the properties pass through the schema here:https://github.com/kestra-io/kestra/blob/develop/ui/src/components/flows/tasks/TaskBasic.vue#L57

So you need to use the property to find the minimum required
Tell me if one part is not clear enough for you, good luck!

**Comment by mounikaperi** [comment]
@Skraye so I should be using this.schema.properties.limit.exclusiveMinimum to be > 0 instead of disabling the component?

**Comment by Skraye** [comment]
If the schema does have a minimum, then yes you should use it, however there should be no minimum

**Comment by mounikaperi** [comment]
@Skraye can you please check now. Implemented using schema property

**Comment by Skraye** [comment]
Its better, but you have missed some information I gave you : 

TaskBasic is a very generic component, so you can not use :
```js
const concurrencyLimit = this.schema.properties.limit;
return concurrencyLimit && concurrencyLimit.exclusiveMinimum
```
Because it does only work for concurrencyLimit, and TaskBasic is not only for this property, its for every property, so you must check the exclusiveMinimum and apply it for every schema that has it

Also, by default you return 1 :
```js
? concurrencyLimit.exclusiveMinimum
 : 1;
```
But what if my other property have no minimum and  can be 0 or negative ? its does not work!

**Comment by mounikaperi** [comment]
that's correct. so can we have this logic enabled only to the property type "integer" so that this doesn't apply to other types?
I can have the exclusiveMinimum called and checked only for component types of integer
The reason to default it to 1 is if we don't have the exclusiveMinimum property always we can return 1 as minimum.
What do we do when we don't have the minimum property available?

**Comment by Skraye** [comment]
If there is no minimum, integer or not, you just don't provide it, try setting it to `null`
If it does not work, you can refer to the default set by the library element plus

**Comment by mounikaperi** [comment]
@Skraye @MilosPaunovic 
Incorporated review comments
can you please check now

**Review by Skraye — APPROVED** [review]
LGTM! Thank you :medal_sports:

**Pull request merged**
