### PR TITLE
chore: upgrade micronaut platform dependencies to 4.6.1

### PR DESCRIPTION
**Pull request by Skraye**

### CODE REVIEW

**Comment by loicmathieu** [comment]
@Skraye the dependabot PR was close because when we migrate to Micronaut 4.6 the webserver just never load.
We previously had this issue in an other Micronaut upgrade, I think at this time we just waited ...

**Comment by Skraye** [comment]
Noted, then for now I'll just force the micronaut-openapi version

**Comment by loicmathieu** [comment]
You can also try to understand what's going on and fix it ;) 
Overriding one of the micronaut module is never a good idea as it may not be incompatible.

**Comment by Skraye** [comment]
@loicmathieu Starting from a fresh build seems to make it work, at least Kestra is up and running fine, you can try it yourself if you want to validate or then just merge

**Pull request merged**
