### PR TITLE
fix/deprecate-listeners

### LINKED ISSUE #1409: Deprecate listeners in favor of triggers
### Feature description

this pattern will be deprecated:

```yaml
id: slackFailureNotifications
namespace: prod
tasks:
  - id: fail
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - exit 1
listeners:
  - conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
    tasks:
      - id: slack
        type: io.kestra.plugin.notifications.slack.SlackExecution
        url: {{envs.slack_webhook}}
        channel: "#general"
```

in favor of triggers:
```yaml
id: slack-global
namespace: com.kestra.monitoring

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ namespace.slack.webhook }}"
    channel: "C02U601DNAJ"
    username: "Kestra"
    iconEmoji: ":kestra:"
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: com.kestra
        prefix: true
```

cc @Ben8t backlog

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #1409

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
The Listener class itself must be deprecated, I think.

**Comment by loicmathieu** [comment]
And all existing listeners also

**Comment by anna-geller** [comment]
Listeners have to be deprecated for several reasons - listing those I'm aware of:
1. they require extra workarounds in the codebase 
2. they are redundant -- there is nothing in listeners that you couldn't do with triggers
3. extra concept that users need to learn (even though they don't have to)

**Comment by brian-mulier-p** [comment]
I can do it but rn it will look ugly on the warning part but as you wish

**Comment by loicmathieu** [comment]
We discussed this this morning and decided to only deprecate the property to avoid too many warnings on the UI.

**Review by loicmathieu — APPROVED** [review]
LGTM

**Pull request merged**
