### PR TITLE
feat(core): add `{{ error.value }}` if the failed taskrun has a value

### LINKED ISSUE #5653: Add pebble function to access taskrun value for which the task failed in ForEach
### Feature description

Take the example flow here. If this flow breaks during an iteration of ForEach, we should be able to access the value at the current `{{taskrun.value}}` . However currently this is not passed through as we are no longer in the flowable context

```
id: errors
namespace: demo

variables:
  current_iteration: ""

tasks:
- id: iterateObjects
  type: io.kestra.plugin.core.flow.ForEach
  concurrencyLimit: 1
  values: '["/tmp/kestra-wd/data/good.csv", "/tmp/kestra-wd/data/error.csv"]'
  tasks:
    - id: debugCurrentIteration
      type: io.kestra.plugin.core.debug.Return
      format: "{{ taskrun.value }}"

    - id: printFileName
      type: io.kestra.plugin.core.log.Log
      message: Let's read CSV {{ taskrun.value }}

    - id: downloadFile
      type: io.kestra.plugin.core.http.Download
      uri: '{{ taskrun.value }}'
  errors:
    - id: printErrorMsg
      type: io.kestra.plugin.core.log.Log
      message: Error reading {{ taskrun.value }}
```

### PR DESCRIPTION
**Pull request by Skraye**
close #5653

### CODE REVIEW

**Review by loicmathieu — CHANGES_REQUESTED** [review]
This is one way of doing that, but it misses value for flowable tasks.

I think it would be better to make flowable tasks pass the value themself so that the standard `taskRun.value` works inside ForEach/EachParallel/EachSequential.

**Comment by Skraye** [comment]
@loicmathieu Maybe I didnt get your point but this does work for Flowable as it is the point of this PR
Modifying the task run would require modifying a lot of stuff in the flowableUtils and may not work for new flowable

**Comment by loicmathieu** [comment]
You only add the value in the error from the Worker, this is far from being the only places where we create an error.
So if an error is inside a flowable that is itself inside another flowable, the error will be created by the executor not the worker so it will not be present.

**Comment by anna-geller** [comment]
can we merge it? Will wants to add a docs page for Task Runs

**Comment by tchiotludo** [comment]
I will be honest, I don't like the base implementation, that need to be fixed. 
The copy on the Execution is a [mistake](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/models/executions/Execution.java#L110) that need to be fixed, I don't get the point of copying something that is [already present](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/models/executions/TaskRun.java#L61) at the `TaskRun` level, please remove the one on execution. 

Instead just at the `RunContext` level, just get the latest one, to feed the `{{ error.value }}` from this search. 

Also the `stacktrace` should be removed, stacktrace is second level of debugging and is already visible on the logs page, don't make sense to overflood the main execution object with the stacktrace.

**Comment by loicmathieu** [comment]
> The copy on the Execution is a [mistake](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/models/executions/Execution.java#L110) that need to be fixed, I don't get the point of copying something that is [already present](https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/models/executions/TaskRun.java#L61) at the TaskRun level, please remove the one on execution.

We only use the taskrun to convey the ExecutionError to the Execution, in the end, there will always be only one execution error which will be at the execution level. This is to be able to set an ExecutionError from the Executor, which is important as not all errors come from a task run. You can think of it as if transmetting the error from the task run to the execution is a nice to have, the most important part of this change is to be able to catch error that didn't comes from a task run because today those are silent.

> Also the stacktrace should be removed, stacktrace is second level of debugging and is already visible on the logs page, don't make sense to overflood the main execution object with the stacktrace.

This was especially asked in the issue that describes this new feature. It allows to display the stack trace in the execution error widget in the UI and also include it in any notification message (for example, Slack or email alert). To avoid overflowing the execution context, the stack trace only contains the first 10 lines.

**Comment by loicmathieu** [comment]
The end result of the new ExecutionError is this widget in the Execution Overview page, note that here the error comes from the Executor not from a task run.

image

When you click on the carret your have the partial call stack that will appear.

image

**Comment by tchiotludo** [comment]
I really don't like to copy the error and even more the execution stacktrace on the execution object, it's totally out of the purpose of the execution model to bring log, that will be outside of the LogEntry and that is duplicate. 
LogEntry is the only way to store error and stacktrace. 

We need to reevaluate the whole feature!

**Comment by loicmathieu** [comment]
A stacktrace is around 1KB as we only take the first 10 lines, it's more an error detail than a stacktrace.

The idea is to have the "last error" inside the execution context so user can use it in notification plugins, and we can display it inside the execution UI (again, this cover errors which are from the executor and that didn't always have a log in the UI).

The current code does two things:
1. Add an execution error in the execution from exception "out of any task run"
2. Add an execution error if a taskrun fails, it will be overridden if multiple taskrun fails by the last failure

I think both are super useful.

For 2., the implementation adds and ExecutionError inside the taskrun but we can definitely add it inside the WorkerTaskResult instead so it will not be part of the execution context.

**Comment by tchiotludo** [comment]
We should seperate the issue, the ui is already possible easily, we already have this errors directly on the logentry, we need to: 
- display error that is linked to an execution and not linked to a taskrun, and this is already possible without any change to the model context, it should be done: 
  - on the log page 
  - on the overview using the existing design from this issue. 
- for the notification, we could easily introduce a proxy function in the `RunContext` without polluting the whole execution `{{ error.lastError }}` => fetch latest error from the repository

**Pull request closed without merging**
