### PR TITLE
Feat/buttons at top

### PR DESCRIPTION
**Pull request by brian-mulier-p**
based on https://github.com/kestra-io/kestra/pull/1861
closes https://github.com/kestra-io/kestra/issues/1334

At top:
image

Partial scroll (not going > the base offset of the buttons), no bar:
image

Scroll beyond base offset of buttons, original bottom bar at top:
image

### CODE REVIEW

**Review by tchiotludo — CHANGES_REQUESTED** [review]
- Some padding is missing when fixed:
image
- responsive layout failed: 
image
- you don't remove the padding bottom that we leave for the bottom bar:
image

**Review by tchiotludo — CHANGES_REQUESTED** [review]
We have still a lot of issues with some overflow: 
image
Even more, we lose the click on the breadcrumb. 
We need to refactor this more largely and rely only on css to handle the positioning

**Comment by brian-mulier-p** [comment]
The overflow handling occurs on small screen sizes I guess you're on an in-between res. Nico told me to put the buttons a bit underneath on small screens so I did it, but I think you fall off on a res which don't occur unless in devtools mode

**Comment by Nico-Kestra** [comment]
Capture d’écran 2023-08-21 à 15 45 22
Hey Brian, wdyt about "/.../" to cut this long breadcrump and maybe have on right one principal button and others options into one button "more"

**Comment by brian-mulier-p** [comment]
Looks okay for me, WDYT @tchiotludo

**Comment by tchiotludo** [comment]
@Nico-Kestra @brian-mulier-p hard to do, since we cut not at the end but at the beginning, maybe we could take some inspiration on github one : 
image

**Comment by Nico-Kestra** [comment]
Capture d’écran 2023-08-21 à 16 12 23
More simple.

**Comment by brian-mulier-p** [comment]
Draft for now as the Figma changed

**Pull request closed without merging**
