### PR TITLE
fix(UI): Date parsing should not apply when rendering vars as it coul…

### LINKED ISSUE #1070: 4-digits String as inputs are considered as a date when displayed
### Expected Behavior

My usecase was to get a warehouse id as input which can be digits-only or alphanumerics-composed.
It should display String as raw IMO ? Especially since there is a type: DATE

### Actual Behaviour

image
image

As you can see, my input is parsed and displayed as date in the input information of the execution while it is treated as my raw String inside my flow.

### Steps To Reproduce

In the quickstart configuration (v0.8.0-SNAPSHOT), run the given example flow and check the executions tab

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): MacOS
- Java Version (If not docker): Under docker

### Example flow

id: numberAsDate
namespace: simple.test
inputs:
  - name: numberAsString
    type: STRING
    defaults: "2685"
tasks:
  - id: print
    type: io.kestra.core.tasks.debugs.Echo
    format: "{{inputs.numberAsString}}"

### PR DESCRIPTION
**Pull request by brian-mulier-p**
…d lead to confusion

Was wondering about trying to find out a rule to parse it in certain case but it feels too tricky and I think that in any case you would prefer to see raw inputs and outputs to prevent confusion

close #1070

### CODE REVIEW

**Comment by tchiotludo** [comment]
I really want to keep the auto date parsing, since this component is used everywhere.
Maybe a simple regexp like `^(?:\d{4})-(?:\d{2})-(?:\d{2})` will do the trick to be sure it's a date or a datetime?

**Comment by brian-mulier-p** [comment]
That's what I thought at first but navigating in the app and regarding where the code is used, I didn't find any inconvenience removing it ?
image
image

**Comment by tchiotludo** [comment]
For every trigger (schedule), we will lose the major improvement on date display

**Comment by brian-mulier-p** [comment]
I didn't use triggers yet but I see the point now, sorry, I will add the regex

**Comment by brian-mulier-p** [comment]
I've added the regex filter :)

**Pull request merged**
