### PR TITLE
fix(ui): Same filter can be applied multiple times

### LINKED ISSUE #6028: Same filter can be applied multiple times
### Describe the issue

Filter duplication should no be allowed
image

### Environment

- Kestra Version: develop

### PR DESCRIPTION
**Pull request by kratosmy**
### What changes are being made and why?

closes #6028
---

### How the changes have been QAed?

image

### CODE REVIEW

**Comment by kratosmy** [comment]
@anna-geller could you please help review?

**Comment by anna-geller** [comment]
I actually thought the way to implement it would be to make the namespace dropdown not available if one namespace filter has already been added 

So more like disabling the filtering option instead of raising an error - WDYT? No strong opinions 

For code review, Milos assigned himself 👍

**Comment by kratosmy** [comment]
> I actually thought the way to implement it would be to make the namespace dropdown not available if one namespace filter has already been added
> 
> So more like disabling the filtering option instead of raising an error - WDYT? No strong opinions
> 
> For code review, Milos assigned himself 👍

Good point, actually I didn't particularly consider the business context， but as you said, If multiple namespaces do not exist, disabling the filter should be better.

**Comment by MilosPaunovic** [comment]
Actually, I think the best solution here would be to, if, for example, you already have a namespace filter selected, and considering the namespace filter has `multiple: false`, still allow the ability to choose the namespace but to replace the existing value. WDYT @anna-geller?

**Comment by anna-geller** [comment]
Great idea Milos! 👍

**Comment by kratosmy** [comment]
> Actually, I think the best solution here would be to, if, for example, you already have a namespace filter selected, and considering the namespace filter has `multiple: false`, still allow the ability to choose the namespace but to replace the existing value. WDYT @anna-geller?

@MilosPaunovic I agree. So will you do the implementation or let me finish it?

**Comment by MilosPaunovic** [comment]
I'd definitely appreciate if you can tackle it @kratosmy!

**Comment by kratosmy** [comment]
> I'd definitely appreciate if you can tackle it @kratosmy!

sure!

**Comment by MilosPaunovic** [comment]
Hey @kratosmy, is this ready for review or you still haven't had the chance to work on the agreed specs?

**Comment by kratosmy** [comment]
> Hey @kratosmy, is this ready for review or you still haven't had the chance to work on the agreed specs?

Hi , @MilosPaunovic , i am busy this week, i will be free on Sunday and continue my work.

**Comment by MilosPaunovic** [comment]
Hey @kratosmy, so, we're almost there!

The only thing left to be changed is the filter with `multiple` true. When you go to the `Executions` page, and select `State` filter and chose let's say two values, close the popup, open it again, go to `State` and try to add one more (to have total of 3), it removes the previous two.

Could you handle this one also for me to be able to merge it?

**Comment by kratosmy** [comment]
> Hey @kratosmy, so, we're almost there!
> 
> The only thing left to be changed is the filter with `multiple` true. When you go to the `Executions` page, and select `State` filter and chose let's say two values, close the popup, open it again, go to `State` and try to add one more (to have total of 3), it removes the previous two.
> 
> Could you handle this one also for me to be able to merge it?

sure

**Review by MilosPaunovic — APPROVED** [review]
LGTM! Thanks for the contributions @kratosmy! 🚀

**Pull request merged**
