### PR TITLE
feat(ui): Update components to handle error tasks and render plugin icons

### PR DESCRIPTION
**Pull request by rohitg00**
### What changes are being made and why?

Update components to handle error tasks and render plugin icons
- **Outputs.vue**
  - Add logic to render plugin icons for error tasks
  - Update component to handle error tasks correctly

- **Vars. vue**
  - Modify component to render plugin icons for error tasks
  - Ensure component handles error tasks correctly

- **VarValue.vue**
  - Update component to display icons for error tasks
  - Ensure component handles error tasks correctly

- **Overview.vue**
  - Modify component to display outputs section with correct icons for error tasks
  - Ensure component handles error tasks correctly

### CODE REVIEW

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
hi @rohitg00,

I've started checking your PR, but it does not seem to fix anything that this issues requires. Can you try and sort it out?

image

**Comment by MilosPaunovic** [comment]
Any news here, are you going to be able to work on this soon @rohitg00?

**Comment by rohitg00** [comment]
Yes! Can you please share what all things are still pending to implement the requirement?

**Comment by MilosPaunovic** [comment]
> hi @rohitg00,
> 
> I've started checking your PR, but it does not seem to fix anything that this issues requires. Can you try and sort it out?
> 
> image

**Comment by rohitg00** [comment]
Thanks, I'll start making changed by weekend

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
We are not using `React` in this project, but `Vue`. This needs to be re-written before I can do a review.

**Comment by anna-geller** [comment]
@MilosPaunovic can this be merged or fixed by us?

**Comment by MilosPaunovic** [comment]
Not without a proper review, and with this pace, I won't have time before Tuesday release.

**Review by MilosPaunovic — APPROVED** [review]

**Pull request merged**
