### PR TITLE
feat(ui) : Change edge type from `smoothstep` to `bezier` #5350

### PR DESCRIPTION
**Pull request by sanketmagar2001**
changing edge type from `smoothstep` to `bezier`.

### What changes are being made and why?

 Changing edge type from 'smoothstep' to 'bezier' for more readable in complex dependency graph.
---

### How the changes have been QAed?

---

### Setup Instructions

Relates to https://github.com/kestra-io/kestra/issues/5350.

### CODE REVIEW

**Comment by sanketmagar2001** [comment]
PR in ui-libs :[kestro-io/ui-libs changes](https://github.com/kestra-io/ui-libs/pull/94)

**Comment by Skraye** [comment]
Hello @sanketmagar2001, unfortunately, the issue is still there : 
image

**Comment by Skraye** [comment]
@sanketmagar2001 Hello, any update on this?

**Comment by sanketmagar2001** [comment]
Hi @Skraye, apologies for the delay 🙂. I was celebrating the festive season in our country, so I couldn't work on this during that time.

**Comment by sanketmagar2001** [comment]
We can also apply the approach 2 which I have mention : Calculate Edge Curvature and Offset , this may work as we can calculate the offset from the node . I will try this out , and let you know . will also update the PR once done.

**Comment by sanketmagar2001** [comment]
for now let's try with hard coded values , if this does not work . we can calculate the offset and curvature from source to target node.

**Comment by MilosPaunovic** [comment]
@sanketmagar2001 Have you tested the `hardcoded values` approach? Does it behave in the way we would like it?

**Review by MilosPaunovic — APPROVED** [review]

**Pull request merged**
