### PR TITLE
chore(ui): Improvement in Welcome Page.

### LINKED ISSUE #6056: Improve the Welcome Page
With the new sidebar, the old welcome page no longer fits. 

image

The button "Watch video" should point to this video https://www.youtube.com/watch?v=a2BZ7vOihjg 

Here is a new design:

Dashboard-Welcome

Dashboard-Welcome-1

Dashboard-Welcome-2

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Closes https://github.com/kestra-io/kestra/issues/6056

image
image

I was unable to render the top-nav-bar component for welcome page. could you please guide ? or when you will add I will get the idea. If needed I will share my code which I was trying to add.

### CODE REVIEW

**Comment by elevatebart** [comment]
Hi @Piyush-r-bhaskar,

Thank you for this work, it's good stuff.
If you want to see an example of how to set a `TopNavBar.vue` component, look at the `Executions.vue` [link on develop](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/executions/Executions.vue#L2-L31)

Basically `<top-nav-bar :title="routeInfo.title"/>` will be the gist of it.

Tell me if you need help setting it up.

**Comment by Piyush-r-bhaskar** [comment]
> Hi @Piyush-r-bhaskar,
> 
> Thank you for this work, it's good stuff. If you want to see an example of how to set a `TopNavBar.vue` component, look at the `Executions.vue` [link on develop](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/executions/Executions.vue#L2-L31)
> 
> Basically `<top-nav-bar :title="routeInfo.title"/>` will be the gist of it.
> 
> Tell me if you need help setting it up.

Thank You @elevatebart 

I tried to use the one from Flows but still could use some guidance . Could you check the code I am adding and suggest please.
[Welcome.txt](https://github.com/user-attachments/files/17942933/Welcome.txt)

**Review by elevatebart — APPROVED** [review]
There was indeed an unforeseen v-if inside of topbar that prevented the navbar from showing up on welcome (even if it was not event on the layout...).

I removed it and pasted your code.

It looks good ! Thank you!

**Comment by elevatebart** [comment]
One nitpick though, if I may be so bold, the background should be a radial-gradient instead of a linear as per the comps.

**Comment by Piyush-r-bhaskar** [comment]
> One nitpick though, if I may be so bold, the background should be a radial-gradient instead of a linear as per the comps.

It could be implemented Barthélémy whenever you say 😊

Thanks so much for reviewing my PR.

**Comment by MilosPaunovic** [comment]
Hey @Piyush-r-bhaskar, are there any follow-ups on Bart's comment, is that already pushed?

**Comment by Piyush-r-bhaskar** [comment]
> Hey @Piyush-r-bhaskar, are there any follow-ups on Bart's comment, is that already pushed?

Hi @MilosPaunovic 


If it's about Radial gradient - then its added.

I have nothing to add more as of now for this PR and awaiting for @elevatebart action to merge if all is good now as he has also made some changes.

**Comment by MilosPaunovic** [comment]
Lovely, thanks for the update @Piyush-r-bhaskar. Now we wait for Bart to find some time to review this and, if alright, merge.

**Review by elevatebart — APPROVED** [review]

**Comment by elevatebart** [comment]
Will merge once the release is cut.

**Pull request merged**
