### PR TITLE
Label Kestra environments

### LINKED ISSUE #1483: Add a custom UI color and label helping to distinguish between development and production environments
### Feature description

As shown in [this great post](https://www.morling.dev/blog/oh_this_is_prod/), it's important to be able to distinguish between development and production environments easily. However, often it's easy to accidentally confuse production and development UIs if they look the same way.

## Proposal
Add an option in the UI settings to set a custom color and label so that users can OPTIONALLY customize Kestra UI based on their environment.

image

image

### PR DESCRIPTION
**Pull request by yuri1969**
Added env name + color settings to set local user-specific labels.

close #1483

### CODE REVIEW

**Comment by anna-geller** [comment]
thank you thank you thank you thank you! ❤️

**Comment by tchiotludo** [comment]
@yuri1969 maybe it could be better to have as a configuration variable? 
I don't think people will want to have a different value for the same instance? 
WDYT?

**Comment by yuri1969** [comment]
@tchiotludo At first, I thought the same - to have the cluster identify itself under a _name_ (a config property => `/api/v1/configs`). Then I realized this was a similar situation to a GUI DB client (think of DBeaver) where you name/label/colorize your _connections_ locally. So it is set locally.

Would there be any other use of the _name_ on the backend/API?

Personally, I have no preference of either choice.

**Comment by yuri1969** [comment]
...and now I've discovered the possibility of having a (quirky) environment label is already present as [kestra.webserver.html-head](https://kestra.io/docs/administrator-guide/configuration/others#kestrawebserverhtml-head-append-some-head-tags-on-the-webserver-application).

**Comment by anna-geller** [comment]
There seems to be a decision bottleneck here - @tchiotludo can you check how can we move forward to get this merged?

**Comment by tchiotludo** [comment]
I've added the global setting and made some adjust, thanks for the contributions :clap:

**Pull request merged**
