### PR TITLE
chore(ui): make the ESLint check a part of the build verification process

### PR DESCRIPTION
**Pull request by yuri1969**
IDE was not happy with all the linting errors/warnings. So this PR:

- attempted to fix all reported Vue/JS linting problems
  - added a rule ignoring unused variables prefixed by `_`
- enabled TypeScript linting
- made the linting a part of the Gradle `check` task

### CODE REVIEW

**Comment by tchiotludo** [comment]
OMG ! 
THanks for that, this is a huge PR that we need to merged quickly! 
I think it's a good idea, but I will triple check with peoples internally tomorrow! 
:clap: :clap: :clap:

**Comment by anna-geller** [comment]
Hi @yuri1969, I'm so sorry this hasn't been merged yet. It seems there was one issue preventing to merge it immediately and then the PR review was abandoned. Given too many conflicts now, we would need to recreate the PR

**Comment by yuri1969** [comment]
@anna-geller Yea, the branches drifted quite a lot. I'll try to deal with the conflicts when I find some time.

**Comment by yuri1969** [comment]
@tchiotludo The PR has been rebased with new linter warnings hopefully fixed 🤞

**Comment by brian-mulier-p** [comment]
Sorry that it didn't get merged before, it got completely lost :'( I had to add some indents over a new rebased file but I think the CI should pass. If it does we merge that :+1:

**Pull request merged**
