### PR TITLE
fix: Return flow outputs in execution API response when wait=true

### PR DESCRIPTION
**Pull request by Malaydewangan09**
### What changes are being made and why?
- Resolved the issue where the execution API endpoint with `wait=true` was not returning the flow outputs as expected.
Ensured that task run outputs are included in the response for executions triggered with the `wait=true` parameter.
Reproduced the flow outputs to match the results from normal execution triggers, aligning the behavior with the expected output.

Fixes issue #5356.

### CODE REVIEW

**Comment by Malaydewangan09** [comment]
Hey @Skraye 
Did you look into it?

**Review by Skraye — APPROVED** [review]
LGTM!

**Comment by Skraye** [comment]
Will merge when CI is green, thank for the contribution :medal_sports:

**Comment by Malaydewangan09** [comment]
Thanks! @Skraye

**Comment by razuro** [comment]
🎉 Yeay! Thanks @Skraye @Malaydewangan09!

**Pull request merged**
