### PR TITLE
Feat: added a slider between editor/(doc||topo) view to adjust div size

### PR DESCRIPTION
**Pull request by Skraye**
You may need to check the visual @Ben8t and give feedback.

### CODE REVIEW

**Comment by brian-mulier-p** [comment]
If you move the slider, when you go back to source only you still have a grey box.
Going to Topology only will remove again grey box.
I will try to fix it along with adding the local storage part

**Comment by tchiotludo** [comment]
take care to store in localStorage with `%` and not in `px` to avoid bug

**Comment by Ben8t** [comment]
linked to https://github.com/kestra-io/kestra/issues/1159

**Comment by brian-mulier-p** [comment]
LGTM

**Review by brian-mulier-p — APPROVED** [review]

**Pull request merged**
