### PR TITLE
Aligned elements in logs tabs 

### LINKED ISSUE #2798: Alignment of logs tabs is not centered
image

### PR DESCRIPTION
**Pull request by riyamustare**
aligned the elements in logs tabs to center closes #2798 
Screenshot 2024-10-09 at 11 55 15 PM

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
@riyamustare Is this ready for review?

**Comment by riyamustare** [comment]
@MilosPaunovic i dont know, i just changed the css code and it is working fine for me, must have did something wrong with commit or pull request, you could tell me ill work on it

**Comment by MilosPaunovic** [comment]
Okay, so, as it is night here, I'll review it in the morning and write a follow-up if necessary, or merge if everything is alright.

**Comment by riyamustare** [comment]
sure, thankyou appreciate it!

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
This is not ideal solution. Let's try to use Bootstrap classes for flex aligning items, chek them out [here](https://getbootstrap.com/docs/5.3/utilities/flex/), and try to make all items aligne to center vertically.

**Pull request closed without merging**
