### PR TITLE
fix(ui) Moved "Language" selection to "Timezone and Date" section next to Timezone and Date and renamed the section #5193

### PR DESCRIPTION
**Pull request by ssparser**
What changes are being made and why?

I have moved the "Language" selection to the "Timezone and Date" section and renamed it to "Language and Region" as asked in the issue, placing it next to the "Timezone" and "Date Format" settings. Additionally, I have translated the new name into the available languages to ensure consistency across the application. This modification addresses issue #5193.

Changes Made:
changes are made to all translations files due to the name change and changed code for language selection from Main Configuration to new Language and Region section.

How the changes have been QAed?
The code for the "Language" selection was already written; I only changed its position from one section to another. 

code that was moved:
```
    <Column :label="$t('settings.blocks.configuration.fields.language')">
                        <el-select :model-value="lang" @update:model-value="onLang">
                            <el-option
                                v-for="item in langOptions"
                                :key="item.value"
                                :label="item.text"
                                :value="item.value"
                            />
                        </el-select>
                    </Column>
```
```
  "localization": {
          "label": "Language and Region",
}
```
This will be my first Contribution if accepted. Thank you

### CODE REVIEW

**Comment by anna-geller** [comment]
thanks so much for contributing!

closes https://github.com/kestra-io/kestra/issues/5193

**Comment by atikkk** [comment]
> thanks so much for contributing!
> 
> closes https://github.com/kestra-io/kestra/issues/5193 
Hey @tanay1337 can you help me in local setup. I am not able to build project on my machine

**Comment by atikkk** [comment]
hey @anna-geller can you help me to setup the project. I am not able to build the project locally

**Comment by anna-geller** [comment]
hey, for this issue everything is done, maybe check [one of these](https://github.com/search?q=org%3Akestra-io+label%3Akind%2Fgood-first-issue+is%3Aopen&type=issues)?

also: https://kestra.io/docs/getting-started/contributing

**Comment by atikkk** [comment]
> hey, for this issue everything is done, maybe check [one of these](https://github.com/search?q=org%3Akestra-io+label%3Akind%2Fgood-first-issue+is%3Aopen&type=issues)?
> 
> also: https://kestra.io/docs/getting-started/contributing

yes, but I want to know how to setup this repository on my machine.

**Comment by atikkk** [comment]
hey @ssparser can you help me to setup the project locally

**Pull request merged**
