### PR TITLE
feat/date-format-settings

### LINKED ISSUE #1166: Add a date format setting
### Feature description

Add a Setting to let the user choose the datetime format (Month:Day:Year / Year:Month:Day / Day:Month:Year / xx/xx/xxxx etc...) - on dashboards, flow executions, etc..

**We must add a settings with predefined format** : 
* YYYY-MM-DD ( follows the ISO 8601 standard, widely used)
* YYYY-MM-DDThh:mm:ssZ ( follows the ISO 8601 standard, widely used)
* MM/DD/YYYY (commonly used in the United States)
* DD/MM/YYYY (commonly used in UE)
* YYYY/MM/DD
* MM/DD/YY

image

### PR DESCRIPTION
**Pull request by brian-mulier-p**
I intentionally did not change the logs date format as I feel like this date should be fully displayed in all case

closes #1166

### CODE REVIEW

**Comment by brian-mulier-p** [comment]
image
image

**Comment by Skraye** [comment]
@Ben8t @anna-geller Do you think every date should be parsed? For example, logs dates?

**Comment by Ben8t** [comment]
> @Ben8t @anna-geller Do you think every date should be parsed? For example, logs dates?

maybe not logs dates (as we usually need granularity here), but otherwise I think yes

**Comment by loicmathieu** [comment]
I think date should be displayed in the browser timezone (so no +02:00).
And we also need to have a way to override the timezone.

**Comment by anna-geller** [comment]
I appreciate the screenshots in the UI PR @brian-mulier-p - so helpful!

**Comment by loicmathieu** [comment]
@anna-geller this PR didn't changed the format on the database nor the API results, so if someone use a tool to extract logs it will still be in the same format (which should be ISO but I didn't check).

**Comment by brian-mulier-p** [comment]
So is it LGTM after all ? :laughing:

**Comment by brian-mulier-p** [comment]
Or maybe I should add the timezone override and we're good ?

**Comment by Skraye** [comment]
See if the timezone can be done quickly.
However I need to test it first

**Pull request merged**
