### PR TITLE
Update InputsForm.vue | radio button styling

### LINKED ISSUE #5619: Review Hover color Tab
### Describe the issue

On hover, the text is completely unreadable.

Capture d’écran 2024-10-23 à 12 18 29

Could you modify this component using the following one:
Capture d’écran 2024-10-23 à 12 25 04
Capture d’écran 2024-10-23 à 12 25 50

Thx!

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

### PR DESCRIPTION
**Pull request by Piyush-r-bhaskar**
Kept the active selection with earlier color to make it more visible.

Closes https://github.com/kestra-io/kestra/issues/5619

### CODE REVIEW

**Review by MilosPaunovic — CHANGES_REQUESTED** [review]
Hey @Piyush-r-bhaskar,

You've went down the more complicated path. Can you just add class to:

```
 <el-radio-group
   :data-test-id="`input-form-${input.id}`"
   v-if="input.type === 'BOOLEAN'"
   v-model="inputsValues[input.id]"
   @update:model-value="onChange(input)"
   class="boolean-inputs w-100"
>
   <el-radio-button :label="$t('true')" :value="true" />
   <el-radio-button :label="$t('false')" :value="false" />
   <el-radio-button :label="$t('undefined')" value="undefined" />
</el-radio-group>
``` 

And handle it in a more simple manner:
```
:deep(.boolean-inputs .el-radio-button) {
   // ...
}
```

**Comment by Piyush-r-bhaskar** [comment]
> Hey @Piyush-r-bhaskar,
> 
> You've went down the more complicated path. Can you just add class to:
> 
> ```
>  <el-radio-group
>    :data-test-id="`input-form-${input.id}`"
>    v-if="input.type === 'BOOLEAN'"
>    v-model="inputsValues[input.id]"
>    @update:model-value="onChange(input)"
>    class="boolean-inputs w-100"
> >
>    <el-radio-button :label="$t('true')" :value="true" />
>    <el-radio-button :label="$t('false')" :value="false" />
>    <el-radio-button :label="$t('undefined')" value="undefined" />
> </el-radio-group>
> ```
> 
> And handle it in a more simple manner:
> 
> ```
> :deep(.boolean-inputs .el-radio-button) {
>    // ...
> }
> ```

Sure @MilosPaunovic ...Let me make the changes. Thank You for checking.

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

I tried to do it other way little complex. I don't know why `:deep` selector is not working.
Also, for the radio-button, default is `border-left: 0` (applies for `:first-child`) too which I had to tweak for `border hover` to work.

I would love to see more changes you suggest 😊

**How it looks:** 

image
image

On Hover
> image

**Review by MilosPaunovic — APPROVED** [review]
Fantastic work, exactly what we were looking for! Thanks again @Piyush-r-bhaskar! 🚀

**Pull request merged**
