### PR TITLE
Change task run value color to white for readability in ForEach task …

### PR DESCRIPTION
**Pull request by mithindev**
### What changes are being made and why?

This PR changes the `small` element color from `--bs-gray-600` in the Gantt and Logs views for improved readability, fixing the visibility issue caused by the previous gray color in `Gantt.vue` and `TaskRunLine.vue`. 

**Closes:** #5445

---

### How the changes have been QAed?

Changes have been tested to ensure task run values are clearly visible.

SCR-20241023-srxb
SCR-20241023-ssae

### CODE REVIEW

**Comment by MilosPaunovic** [comment]
@mithindev What does it look when the theme is set to `Light`?

**Comment by mithindev** [comment]
@MilosPaunovic, This is how it looks in light theme.

image

**Review by MilosPaunovic — APPROVED** [review]
LGTM! 🚀

**Comment by MilosPaunovic** [comment]
Awesome, just wanted to double check with you. Note for any further contributions - if you're doing similar kinds of changes, always check both themes.

Nice work here! 🚀

**Comment by mithindev** [comment]
Roger that! Absolutely 👍

**Pull request merged**
