### PR TITLE
feat(ui): QOL improvement for files editor

### LINKED ISSUE #2342: Allow creating + saving flows from VS Code with full autocompletion (kestra flow schema is currently not preloaded)
Currently, fetching the flow schema requires manual intervention from the user. Fixing that is #1 priority in this issue. 

Then, we need to add an option to allow adding flow files directly to the `_flows` folder.

### LINKED ISSUE #2367: Rename the `flows` Namespace Files directory to `_flows`
### Feature description

This will:
1. Make it clear that this is a directory managed internally by kestra
2. Automatically pin that directory to the top naturally via naming
3. Make CI/CD easier, e.g., allowing to escape that directory when syncing namespace files via GitHub Actions or Terraform

image

### LINKED ISSUE #2374: Warn about unsaved changes in Namespace Files

### LINKED ISSUE #2381: Load default namespace when starting the VS Code editor
Instead of a blank screen, we should load the default namespace:

image

image

this will be more encouraging and easier to start

### PR DESCRIPTION
**Pull request by Skraye**
Link to https://github.com/kestra-io/vscode-kestra/pull/9

Those 2 PRs bring:
* Fix schema download
* Change flow folders to`_flows`
* Display execute button when on a flow file tab
* Allow creation & deletion of flows
* Use default namespace (if one is setup) when loading files editor
* warn unsaved files when leaving editor
* make editor start on a readme, create one if none exist

close #2381 
close #2367 
close #2342
close #2374

### CODE REVIEW

**Review by anna-geller — CHANGES_REQUESTED** [review]
The schema still doesn't load. 

There's also a minor issue with this message:

image

Because the undo command will not work here, the message should be sth like: "Are you sure you want to delete this flow? This action is irreversible. You can not restore the flow once deleted."


Apart from that, everything works as expected:
- default namespace is loaded
- _flows renamed
- creating + executing a flow works
- executions open in a new tab
- readme is nice -- if possible @Skraye we could rename it to README - sorry, I should have said it in the extension's PR 
- deleting a flow works
- editing flows work

**Comment by Skraye** [comment]
@anna-geller As I will need to release a new version of the extension, except the above issue is there anything that must be in the editor before the release ?

**Review by anna-geller — APPROVED** [review]
Schema works now, awesome work!

We still have a couple of days before the release so if you want to avoid rereleasing new versions of the extensions too many times, let's wait a bit. It would be awesome if we could get this one done but not a requirement 👍 https://github.com/kestra-io/kestra/issues/2405 

image

**Comment by anna-geller** [comment]
@tchiotludo Given that all the issues tackled here are bugs that this PR fixes rather than new features, I'm gonna merge as soon as CI passes but feel free to make any changes afterwards if you see potential for improvement on the code side

**Pull request merged**
