### PR TITLE
fix(ui):dependencies count subtract one

### LINKED ISSUE #2422: Subtract one (the flow itself) from the Flow Dependencies count
### Explain the bug

the subflow here has 2 dependencies, not 3:

image

we shouldn't count the flow itself (the child flow)

### Environment Information

- Kestra Version: 0.13.0

### PR DESCRIPTION
**Pull request by EdwardLi-coder**
Fixes #2422

### CODE REVIEW

**Review by anna-geller — APPROVED** [review]
thanks so much!

**Review by tchiotludo — CHANGES_REQUESTED** [review]
take care, the default value is `0` actually, so you will display `-1`

**Comment by EdwardLi-coder** [comment]
> take care, the default value is `0` actually, so you will display `-1`

Thank you. I update it.

**Comment by anna-geller** [comment]
ok, so @EdwardLi-coder could you make a change to first check if there are any dependencies and then subtract 1 only if there is more than 1 dependency where the flow itself is counted as a dependency? 

@tchiotludo do you know the reason why this dependency count is wrong in the first place? just doing -1 doesn't seem to be the right solution

**Comment by tchiotludo** [comment]
@anna-geller in fact, the main issues is true, we count the actual flow, since the actual flow is displayed in the graph, the counter is based on the same api call :rofl:

**Comment by EdwardLi-coder** [comment]
> @anna-geller in fact, the main issues is true, we count the actual flow, since the actual flow is displayed in the graph, the counter is based on the same api call 🤣

So, this method to resolve it is correct, or need to create an API to handle this count.😁

**Comment by tchiotludo** [comment]
0 meaning no link, 
count - 1 is working on all others cases, so the idea of this PR is ok

**Pull request merged**
